#!/usr/bin/env python3
"""
fix_package_structure.py

Utility script to create __init__.py files in ai_generated_contents_candidate
to make it a proper Python package. This is required for -m module syntax.

Usage:
    python -m src.agents.scripts_and_prompts_generation.fix_package_structure
"""

from pathlib import Path
import sys


def create_init_files():
    """Create all necessary __init__.py files."""
    print("="*60)
    print("FIXING PYTHON PACKAGE STRUCTURE")
    print("="*60)
    print()
    
    # Base directories
    base_dirs = [
        Path("ai_generated_contents_candidate"),
        Path("ai_generated_contents_candidate/scripts"),
        Path("ai_generated_contents_candidate/iterations"),
        Path("ai_generated_contents_candidate/prompts"),
    ]
    
    # Find all ontology subdirectories in scripts/
    scripts_dir = Path("ai_generated_contents_candidate/scripts")
    ontology_dirs = []
    if scripts_dir.exists():
        ontology_dirs = [d for d in scripts_dir.iterdir() if d.is_dir() and not d.name.startswith('_')]
    
    # Combine all directories that need __init__.py
    all_dirs = base_dirs + ontology_dirs
    
    created_count = 0
    for directory in all_dirs:
        if directory.exists():
            init_file = directory / "__init__.py"
            if not init_file.exists():
                init_file.write_text("# Auto-generated by fix_package_structure.py\n", encoding="utf-8")
                print(f"[CREATED] {init_file}")
                created_count += 1
            else:
                print(f"[EXISTS] {init_file}")
        else:
            print(f"[WARNING] Directory doesn't exist: {directory}")
    
    print()
    print("="*60)
    if created_count > 0:
        print(f"SUCCESS: Created {created_count} __init__.py files")
    else:
        print(f"All __init__.py files already exist")
    print("="*60)
    print()
    
    # Verify the fix worked
    print("Verifying package structure...")
    print()
    
    # Test if we can import the module
    test_dirs = ["ontosynthesis", "ontomops", "ontospecies"]
    found_any = False
    
    for ont in test_dirs:
        main_script = Path(f"ai_generated_contents_candidate/scripts/{ont}/main.py")
        if main_script.exists():
            found_any = True
            print(f"[OK] {ont}: main.py exists")
            print(f"     You can now run: python -m ai_generated_contents_candidate.scripts.{ont}.main")
    
    if not found_any:
        print("[WARNING] No ontology scripts found in ai_generated_contents_candidate/scripts/")
        print("          Generate scripts first using generation_main.py")
    
    print()


def main():
    """Main entry point."""
    print()
    
    # Check if we're in the project root
    if not Path("src/agents/scripts_and_prompts_generation").exists():
        print("[ERROR] Must be run from project root directory")
        print("        (The directory containing src/agents/scripts_and_prompts_generation)")
        sys.exit(1)
    
    create_init_files()
    
    print("[SUCCESS] Package structure fix complete!")
    print()


if __name__ == "__main__":
    main()

