#!/usr/bin/env python3
"""
fix_package_structure.py

Utility script to create __init__.py files under a generated artifact root
(default: ai_generated_contents_candidate) so `python -m ...scripts.<ont>.main` works.

Usage:
    python -m src.agents.scripts_and_prompts_generation.fix_package_structure
    python -m src.agents.scripts_and_prompts_generation.fix_package_structure \\
        --root ai_generated_contents_pipeline_bundle
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

DEFAULT_ROOT = Path("ai_generated_contents_candidate")


def create_init_files(root: Path = DEFAULT_ROOT):
    """Create all necessary __init__.py files under ``root``."""
    root = Path(root)
    print("="*60)
    print("FIXING PYTHON PACKAGE STRUCTURE")
    print("="*60)
    print(f"Root: {root}")
    print()
    
    # Base directories
    base_dirs = [
        root,
        root / "scripts",
        root / "iterations",
        root / "prompts",
    ]
    
    # Find all ontology subdirectories in scripts/
    scripts_dir = root / "scripts"
    ontology_dirs = []
    if scripts_dir.exists():
        ontology_dirs = [d for d in scripts_dir.iterdir() if d.is_dir() and not d.name.startswith('_')]
    
    # Combine all directories that need __init__.py
    all_dirs = base_dirs + ontology_dirs
    
    created_count = 0
    for directory in all_dirs:
        if directory.exists():
            init_file = directory / "__init__.py"
            if not init_file.exists():
                init_file.write_text("# Auto-generated by fix_package_structure.py\n", encoding="utf-8")
                print(f"[CREATED] {init_file}")
                created_count += 1
            else:
                print(f"[EXISTS] {init_file}")
        else:
            print(f"[WARNING] Directory doesn't exist: {directory}")
    
    print()
    print("="*60)
    if created_count > 0:
        print(f"SUCCESS: Created {created_count} __init__.py files")
    else:
        print(f"All __init__.py files already exist")
    print("="*60)
    print()
    
    # Verify the fix worked
    print("Verifying package structure...")
    print()
    
    # Test if we can import the module
    test_dirs = ["ontosynthesis", "ontomops", "ontospecies", "medical"]
    found_any = False
    
    for ont in test_dirs:
        main_script = root / "scripts" / ont / "main.py"
        if main_script.exists():
            found_any = True
            print(f"[OK] {ont}: main.py exists")
            pkg = root.name
            print(f"     You can now run: python -m {pkg}.scripts.{ont}.main")
    
    if not found_any:
        print(f"[WARNING] No ontology scripts found in {root / 'scripts'}/")
        print("          Generate scripts first using agentic_generation_main (see README).")
    
    print()


def main():
    """Main entry point."""
    print()
    
    # Check if we're in the project root
    if not Path("src/agents/scripts_and_prompts_generation").exists():
        print("[ERROR] Must be run from project root directory")
        print("        (The directory containing src/agents/scripts_and_prompts_generation)")
        sys.exit(1)

    ap = argparse.ArgumentParser(description="Create __init__.py under a generated MCP bundle root.")
    ap.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_ROOT,
        help=f"Artifact root directory (default: {DEFAULT_ROOT})",
    )
    args = ap.parse_args()
    
    create_init_files(args.root)
    
    print("[SUCCESS] Package structure fix complete!")
    print()


if __name__ == "__main__":
    main()

