# Auto-generated by spec_generation.py
import sys
from pathlib import Path

# Import core step extraction rules from tests/step_extraction/prompt.py
# Calculate the project root (5 levels up from this file)
_project_root = Path(__file__).parent.parent.parent.parent.parent
_tests_path = _project_root / "tests" / "step_extraction"

# Add tests path to sys.path if not already there
if str(_tests_path) not in sys.path:
    sys.path.insert(0, str(_tests_path))

# Import the shared rules
try:
    from prompt import STEP_EXTRACTION_CORE_RULES, STEP_EXTRACTION_JSON_OUTPUT
except ImportError as e:
    # If import fails, try importing from the module path
    try:
        from tests.step_extraction.prompt import STEP_EXTRACTION_CORE_RULES, STEP_EXTRACTION_JSON_OUTPUT
    except ImportError:
        # Last resort: define inline (should not happen in normal operation)
        print(f"Warning: Could not import step extraction rules from prompt.py: {e}")
        STEP_EXTRACTION_CORE_RULES = ""
        STEP_EXTRACTION_JSON_OUTPUT = ""

EXTRACTION_SCOPE_1 = '''
Task: Extract all chemical synthesis procedures described in the article. The top-level entity type is ChemicalSynthesis. Output only the synthesis name/identifier and the document context (section or paragraph). Do NOT extract ChemicalInput or ChemicalOutput.

Ontology-anchored constraints:
- Include a synthesis ONLY if its final product can be modeled as a ChemicalOutput that would be linked via ontosyn:isRepresentedBy to <https://www.theworldavatar.com/kg/ontomops/MetalOrganicPolyhedron> (a bare, discrete 0D metal–organic polyhedron: metal node/cluster + organic linker; guests/solvates/adducts are not part of the represented object).
- When evidence is insufficient to assert such representability, EXCLUDE. When uncertain, EXCLUDE.

Inclusion:
- Precursor exception: Also INCLUDE a discrete, isolated 0D precursor cluster if (i) it is synthesized in THIS paper with procedural detail, and (ii) the text explicitly uses it as a reactant to form a MetalOrganicPolyhedron reported in THIS paper. Generic reagents/salts do NOT qualify.
- Route splitting: If the same named product is obtained by distinct procedures, count EACH procedure as a separate ChemicalSynthesis.
- Interconversion: Structural transformations between isolated products (e.g., α↔β) count as separate ChemicalSynthesis entries if the product is isolated and identified in THIS paper.

Hard rules:
1) Scope gate: Pass if product is a bare MetalOrganicPolyhedron (per isRepresentedBy) OR passes the precursor exception above. Otherwise EXCLUDE.
2) Composite/adduct rejection: EXCLUDE host–guest, adducts, co-crystals, inclusions, and solvates. Lexical cues that force exclusion when present in the product label/description: "·", "/", "+", "⊃", "adduct", "co-crystal", "host–guest", "inclusion", "with <guest>", "solvate", "encapsulat".
3) One product per synthesis: Never merge. If the text says “Synthesis of X and Y”, output two lines.
4) Procedure evidence required: The heading or its immediately following paragraph(s) must contain in-paper procedural detail (any of: amounts, solvent names, temperature, time, vessel, pH, workup, isolation) OR an explicit “same as <another synthesis in THIS paper>”. If absent, EXCLUDE.
5) Product concreteness: The product must be a specific instance in THIS paper (unique code/name and/or a concrete formula string and/or an accession identifier such as a CCDC number). Families/archetypes/prototypes without a concrete instance → EXCLUDE.
6) In-paper only: EXCLUDE background or literature-only preparations lacking in-paper procedural detail.
7) Normalization: No LaTeX/TeX commands. Keep plain words like “alpha”. Remove control characters. Normalize whitespace.
8) Different crystal-form qualifiers doesn't mean different synthesis. You should treat them as one synthesis. （XXX-N (something) and (XXX-N (something else)) are the same synthesis.


Polymorph and duplicate control:
- Do NOT split by polymorph, space group, unit cell, crystal system, color, or crystal habit. Only split when the paper describes distinct procedures (different conditions or an explicit second recipe heading).
- Deduplicate by (product code/name, CCDC). If identical, keep one.
- If CCDCs differ but the procedure block is identical and there is no separate recipe heading, treat as ONE synthesis.
- Normalize titles by stripping parenthetical crystal-system/unit-cell qualifiers from the synthesis name.

Decision tests (fail fast, in order):
A) Representability gate: Is the final product a bare MetalOrganicPolyhedron? If YES → proceed. If NO → check precursor exception.
B) Precursor exception: Is it a discrete, isolated 0D precursor cluster synthesized here AND explicitly used in THIS paper to make a MetalOrganicPolyhedron? If YES → proceed. If NO → EXCLUDE.
C) Procedure evidence: In-paper procedural detail or explicit “same as <this paper’s synthesis>”? If NO → EXCLUDE.
D) Composite/adduct filter: Any composite/adduct/host–guest/solvate cue that remains part of the named product? If YES → EXCLUDE.
E) Concreteness: Unique, concrete instance (code/name/formula/identifier) in THIS paper? If NO → EXCLUDE.
F) Polymorph/duplicate control: Apply the rules above to avoid splitting by crystal form and to deduplicate.
G) If all YES → INCLUDE (count distinct routes and interconversions as separate entries).

Output format (plain text, one line per synthesis):
ChemicalSynthesis — <identifier or name of the output from the paper; use the proper product code/name, check through the paper to find proper names, don't use only numbers, without crystal-form qualifiers, short name XXX-Y is preferred for the main name, but also include other names>
Nothing else. 
'''


EXTRACTION_SCOPE_2 = """
TASK
Extract CHEMICAL INPUTS and CHEMICAL OUTPUT. Keep it simple: only include substances explicitly stated as inputs in the described step. Do not infer from product formulas.


CORE RULES
1) INPUTS and OUTPUTS-ONLY: Include a substance only if the text lists it as an input or output in the step.
2) SPLIT MIXTURES: If a mixture is stated as an input (e.g., “A/B”, “A:B = x:y”), output separate ChemicalInputs records for each component.
3) MOP→MOP TRANSFORMATION: For a transformation from pre-isolated MOP a to MOP b, list only MOP a as the ChemicalInputs block.
4) NO BACKFILL: Do not add components solely because they appear in the product name or composition if they were not stated as inputs.
5) Make sure you check the given entity_label and the output name/identifier are the matching exactly. If that went wrong, your entire result will be wrong. You must check multiple times to make sure you choose the correct one. This should be the first step you take, don't proceed unless you are sure you have the correct one.
6) Take your time and make sure you put everything right, revise the result multiple times if necessary.
7) CCDC HANDLING (iter2): Do NOT search for or include CCDC numbers in iter2. Leave the Representation field blank. CCDC resolution is deferred to iter2_1.

FORMULA LOOKUP POLICY
If a formula for any input or product is not stated in the paper, look it up in reliable sources such as PubChem, ChemSpider, or vendor SDS. Annotate provenance as one of:
(as stated)
(looked up: <source or ID>)
(derived: <brief basis>)
Do not invent compositions.

TEXT PARSING
Split mixed media and mixtures into separate candidates. Accept only proper chemical names. Reject placeholders such as atmosphere, solvent, mixture, solution, filtrate, supernatant, or product nicknames.

OUTPUT
Single fenced code block. Structured bullet list. Use these fields and order. Use N/A if not reported.

ChemicalInputs:
- Name: <as written>
- Alternative Names: <semicolon-separated aliases from text or N/A> **Spare no effort to find all aliases mentinoed in the paper (It may appears elsewhere too.), strictly use semicolon as the separator, never comma or any other character**, look up the alias, also look up via external sources. 
- Amount: <as written, include units if given, include all amounts in different units>, make sure you include all the values representing the amount in all units. **Critial**: there might be a trace of "same as" for the description of the synthesis, you must make sure you make the correct trace and find the right amount. 
In addition, if it is a mixture with ratio provided, you must must do the calculation and put the amount for each component in the mixture, 2 digits after the decimal point.
Don't put the original amount in the amount field, put the calculated amount for each component in the mixture.

If for a mixture of solvents, and not enough information is provided for calculating the amount, you should put the amounts as N/A.

However, you are not allowed to derive amount in other units, only put the mentioned one/ones.  



- Formula: <formula> (<as stated | looked up: <source or ID> | derived: <basis>>)
- Description: <concise functional role such as metal cluster precursor or organic linker>
- Purity: <as written or N/A>
- Supplier: <named vendor | N/A>

Repeat the seven-line ChemicalInputs block for each included input.

ChemicalOutput:
- Identifier: <as written>, usually a short code like name, like XXX-1, XXX-2, etc. **MUST BE THE SAME AS THE GIVEN ENTITY_LABEL"
- Name: <as written for product>
- Formula: <as stated | looked up: <source or ID> | derived: <basis>>
- Representation:  

Put exactly **ONE** ChemicalOutput block for the output. 

FORMATTING RULES
Keep field labels exactly as shown. One blank line between blocks. Do not include JSON, tables, or extra commentary. Split mixed media into separate records. Never emit combined names such as DMF:MeOH.
"""

# Assemble EXTRACTION_SCOPE_3 using imported core rules
EXTRACTION_SCOPE_3 = f'''
You are an expert at extracting synthesis steps from chemistry texts. Analyze the provided synthesis text for the entity.

{STEP_EXTRACTION_JSON_OUTPUT}

{STEP_EXTRACTION_CORE_RULES}
'''


EXTRACTION_SCOPE_3_1 = '''
Goal
Extract all operational step DETAILS for one specified ChemicalSynthesis, using the step types from iter3 as a guide. Preserve order. Output plain text only (no JSON, no code fences, no explanations).

**CRITICAL CONSTRAINT**: You MUST use the EXACT step types and order from the iter3 results provided to you. 
- DO NOT add new steps
- DO NOT remove steps
- DO NOT change step types (e.g., do not change "Add" to "Dissolve" or vice versa)
- ONLY add details to the existing steps (vessel, environment, duration, equipment, parameters)
- The number of steps in your output MUST exactly match the number in iter3 results

Scope
- Top entity: ChemicalSynthesis only. Exclude other syntheses, ligand prep, workups, characterization.
- Steps are actions only. Names, yields, formulas, narrative are not steps.
- Use the step types provided from iter3 as ABSOLUTELY AUTHORITATIVE. Your task is ONLY to add details to these steps, not to re-extract or re-interpret them.

Allowed step types
Add, HeatChill, Evaporate, Sonicate, Dissolve, Crystallize, Transfer, Separate, Filter, Dry, Stir.

VESSEL TRACKING (critical)
- Track which vessel each step uses. If the paper mentions named vessels (e.g., vial 1, Parr autoclave), maintain that assignment.
- Every step MUST have a vessel_name. If not explicit, inherit from the previous step.
- Transfers between containers increment vessel ids (Vessel 1 → Vessel 2, etc.). Do not renumber later.
- Don't assume transfer unless the paper explicitly states it.

Vessel Type rules:
- If there is no vessel type explicity stated in other steps, but one step uses a specific vessel, you must confidently infer the vessel type from the step for **all steps** to be this vessel type.
- Never ever put a vessel type that is not explicitly stated in the paper.
- If steps have different vessel types, you should assign different vessel names to the steps.
- Take the paper content as the authoritative source, do not make up any information.


Atmosphere and agitation

- Atmosphere = gas in direct contact with the mixture for that step.
- If a gas or vacuum is explicitly stated, set it and propagate until changed.
- Gas stated → vessel_environment="<gas>", underVacuum=false.
- Vacuum stated → vessel_environment="n/a", underVacuum=true.
- If sealed and no internal gas is stated → vessel_environment="n/a", sealed_status=true, underVacuum=false. Ignore phrases like “cool the sealed vessel in air.”
- Do not infer inert or vacuum unless explicit.
- Stirring is modeled via stirring_status on the relevant step; do not create standalone Stir steps.
- **Critical**: Don't put "air" unless it is explicitly stated, use "not stated" instead.

Sealed or not: 

- For teflon-lined stainless-steel vessel or reactors or autoclaves, it is always sealed for heating up but not sealed for cooling down.
- For other vessels, only put sealed_status=true if it is explicitly stated in the paper.
- Capped vial ≠ sealed. If only capped or otherwise open to lab air, and no gas is stated → vessel_environment="not stated", sealed_status=false, underVacuum=false.



Required fields per step (emit all if stated; use "not stated" if missing)
- step_type (one of the allowed step types, matching iter3 guidance)
- order (1..N, contiguous, matching iter3 order)
- synthesis_label (exact entity_label)
- vessel_name (Vessel 1, Vessel 2, … or explicit name)
- vessel_environment (Strictly only Air/Ar/Vacuum/not stated), don't use "air" unless it is explicitly stated, use "not stated" instead.
- duration (e.g., "12 h" or "not stated")
- parameters (only schema keys for that step type; omit irrelevant keys)

Parameter schema (only these keys under parameters)
- HeatChill: target_temperature, temperature_rate, pressure_or_vacuum, sealed_status, stirring_status
- Add: substance, amount_or_concentration, target_pH, layered_status, stirring_status
- Evaporate: temperature, pressure, to_volume, removed_species
- Dry: drying_agent, temperature, pressure, method
- Filter: medium_or_method, washing_solvent, repeated_status, vacuum_filtration
- Transfer: from_vessel, to_vessel, transferred_amount, layered_transfer
- Separate: separation_type, solvent_or_phase
- Dissolve: solvent, concentration_or_ratio, temperature
- Crystallize: target_temperature, method
- Stir: stirring_speed, temperature (if applicable)

Output format (plain text; no JSON, no tables, no code fences)
- First line: ChemicalSynthesis — <exact label of this procedure>
- Then a section "Steps:" with one line per step as:
  <order>) <step_type> | vessel_name: <...> | vessel_environment: <...> | duration: <...> | parameters: <key>=<value>; <key>=<value>
- Keep the exact wording from the paper where applicable; normalize whitespace only.
- Match the step count and order from iter3 guidance.
'''


EXTRACTION_SCOPE_3_2 = '''
Goal
Update and enrich the iter3 step results (from iter3_results/iter3_hints_<entity>.txt) with additional details, specifically vessel types for each step. Use the iter3_hints file as the base and ONLY add missing information.

**CRITICAL CONSTRAINT**: You MUST preserve the EXACT step types and order from the iter3_hints file provided to you.
- DO NOT add new steps
- DO NOT remove steps  
- DO NOT change step types (e.g., do not change "Add" to "Dissolve" or "HeatChill" to "Stir")
- ONLY add details to the existing steps (vessel_type, duration, atmosphere, etc.)
- The number of steps in your output MUST exactly match the number in iter3_hints
- This is an ENRICHMENT task, not a re-extraction task

Input
- You will receive the iter3_results/iter3_hints_<entity>.txt file content as the authoritative base
- This file contains the step types and order that you MUST preserve
- You will also receive the paper content to extract additional details

Scope
- Top entity: ChemicalSynthesis only (matching the entity in iter3_hints)
- Update existing steps from iter3_hints ONLY; absolutely do not add or remove steps
- Maintain the exact step order and step types from iter3_hints

Vessel Type rules:
- If there is no vessel type explicity stated in other steps, but one step uses a specific vessel, you must confidently infer the vessel type from the step for **all steps** to be this vessel type.
- Never ever put a vessel type that is not explicitly stated in the paper.
- If steps have different vessel types, you should assign different vessel names to the steps.
- Take the paper content as the authoritative source, do not make up any information.


Task: For each step in iter3_hints
1) Identify the vessel type used for this step
   - Common vessel types: round-bottom flask, vial, beaker, Teflon-lined stainless-steel autoclave, sealed tube, etc.
   - If multiple steps use the same physical vessel, they should have the same vessel type
   - If not explicitly stated, infer from context (e.g., "heated at 150°C" suggests autoclave or sealed tube)

2) Add any other missing step-level details:
   - Temperature specifics
   - Duration if missed in iter3
   - Atmosphere/environment details

Evidence
- Use only facts stated in this paper for this synthesis
- Do not invent vessel types
- Use "not stated" only if truly unmentioned and cannot be reasonably inferred

Output format (plain text, no JSON, no code fences)
- First line: ChemicalSynthesis — <exact label matching iter3_hints>
- Then a section "Steps:" with one line per step:
  <order>) <step_type> | vessel_type: <...> | vessel_name: <...> | vessel_environment: <...> | duration: <...> | other_details: <...>
- Preserve all information from iter3_hints and ADD vessel_type and any other missing details
- The step_type for each order MUST match exactly what is in iter3_hints
- Match the exact step count and order from iter3_hints
'''


EXTRACTION_SCOPE_4 = '''
Goal
Extract ONLY the yield information for one specified ChemicalSynthesis.

Top-level and scope
- Top-level entity type: ChemicalSynthesis
- Work on this single procedure only
- Extract ONLY yield data; no equipment, no steps, no other information

What to extract
Yield (REQUIRED):
- Extract every explicit yield percentage reported for this procedure
- Record the numeric value(s) as written and any explicit qualifiers
  (e.g., "isolated yield", "crystalline yield", "overall yield", "based on <reagent>")
- If multiple yields are given for the same product run, list each with its qualifier
- Do not calculate yields from masses or moles
- If no percentage is stated, write "not stated"

Evidence
- Use only facts explicitly stated for this procedure in this paper
- Do not calculate or infer yields
- If the text references another synthesis for yield (e.g., "same yield as X"), 
  copy the yield value and note the reference

Normalization
- Preserve author wording for qualifiers
- Normalize whitespace; remove control characters
- Do not use LaTeX/TeX notation
- Keep percentage values exactly as written (e.g., "65%", "65 %", "65 percent")

Output format (plain text, no JSON, no code fences)
- First line: ChemicalSynthesis — <exact label of this procedure>
- Then a section "Yield:" listing the percentage value(s) with any qualifiers, or "not stated"
- If multiple yields: list each on a separate line with its qualifier
- Example:
  ChemicalSynthesis — VMOP-18
  
  Yield:
  65% (based on H3TATB)
'''
 

# Pre-extraction of raw relevant text spans (used before step extraction)
# This prompt template is dynamically formatted based on entity_label to match llm_based.py behavior
# Note: entity_label and paper content are appended at runtime in mcp_run_agent_hint_only_dynamic.py
EXTRACTION_SCOPE_6_PRE_EXTRACTION = """
Extract the ORIGINAL TEXT spans from the paper that describe the synthesis procedure for the specified entity only.
- Strictly include only content relevant to the entity_label's procedure; exclude other entities or unrelated sections.
- Include global experimental conditions, e.g., "The experiments were performed under xxx", you must include the global experimental conditions in the pre-extraction. Note that 
this information might appear in other sections of the paper, you must include it in the pre-extraction. Read all contents carefully to find the global experimental conditions.

- Aggregate all relevant snippets even if scattered across the paper; preserve original wording verbatim.

- CRITICAL: If the text contains vague references (e.g., 'above-mentioned procedure', 'same method as', 'similar to the synthesis of', 'prepared as described for', 'following the procedure'), you MUST:
  1) First include the original sentence with the reference
  2) Then add a clear separator line: 'The "[referenced phrase]" refers to the following content:'
  3) Then include the FULL referenced synthesis text
  Example: If text says 'using the above-mentioned procedure', output:
    [Original sentence with reference]
    The "above-mentioned procedure" refers to the following content:
    [Full text of the referenced procedure]
- Preserve order as they appear in the paper; separate non-contiguous snippets with a blank line.
- Do NOT summarize or paraphrase; return only the raw text excerpts with clear reference resolutions.
- Output ONLY the text (no commentary, no code fences, no JSON).
"""

# Pre-extraction prompt for transformations (when entity_label indicates transformation)
# Note: entity_label and paper content are appended at runtime in mcp_run_agent_hint_only_dynamic.py
EXTRACTION_SCOPE_6_PRE_EXTRACTION_TRANSFORMATION = """
Extract the ORIGINAL TEXT spans from the paper that describe the TRANSFORMATION/POST-SYNTHETIC procedure for the specified entity only.
- SPECIAL RULE FOR TRANSFORMATIONS: Extract ONLY the transformation procedure itself (the steps that convert material A to material B).
- Include global experimental conditions, e.g., " The experiments were performed under xxx", you must include the global experimental conditions in the pre-extraction. Note that this information might appear in other sections of the paper, you must include it in the pre-extraction. Read all contents carefully to find the global experimental conditions.

- DO NOT trace back to or include the original synthesis of the starting material.
- Example: For 'transformation VMOP-α to VMOP-β', extract only the steps that transform VMOP-α into VMOP-β, NOT the synthesis of VMOP-α.
- Strictly include only content relevant to the entity_label's procedure; exclude other entities or unrelated sections.
- Aggregate all relevant snippets even if scattered across the paper; preserve original wording verbatim.
- If the transformation text mentions the starting material name (e.g., 'VMOP-α was used'), do NOT trace back to its synthesis.
- Preserve order as they appear in the paper; separate non-contiguous snippets with a blank line.
- Do NOT summarize or paraphrase; return only the raw text excerpts with clear reference resolutions.
- Output ONLY the text (no commentary, no code fences, no JSON).
"""
