# Auto-generated by spec_generation.py
EXTRACTION_SCOPE_1 = '''
Task: Extract all chemical synthesis procedures described in the article. The top-level entity type is ChemicalSynthesis. Output only the synthesis name/identifier and the document context (section or paragraph). Do NOT extract ChemicalInput or ChemicalOutput.

Ontology-anchored constraints:
- Include a synthesis ONLY if its final product can be modeled as a ChemicalOutput that would be linked via ontosyn:isRepresentedBy to <https://www.theworldavatar.com/kg/ontomops/MetalOrganicPolyhedron> (a bare, discrete 0D metal–organic polyhedron: metal node/cluster + organic linker; guests/solvates/adducts are not part of the represented object).
- When evidence is insufficient to assert such representability, EXCLUDE. When uncertain, EXCLUDE.

Inclusion:
- Precursor exception: Also INCLUDE a discrete, isolated 0D precursor cluster if (i) it is synthesized in THIS paper with procedural detail, and (ii) the text explicitly uses it as a reactant to form a MetalOrganicPolyhedron reported in THIS paper. Generic reagents/salts do NOT qualify.
- Route splitting: If the same named product is obtained by distinct procedures, count EACH procedure as a separate ChemicalSynthesis.
- Interconversion: Structural transformations between isolated products (e.g., α↔β) count as separate ChemicalSynthesis entries if the product is isolated and identified in THIS paper.

Hard rules:
1) Scope gate: Pass if product is a bare MetalOrganicPolyhedron (per isRepresentedBy) OR passes the precursor exception above. Otherwise EXCLUDE.
2) Composite/adduct rejection: EXCLUDE host–guest, adducts, co-crystals, inclusions, and solvates. Lexical cues that force exclusion when present in the product label/description: "·", "/", "+", "⊃", "adduct", "co-crystal", "host–guest", "inclusion", "with <guest>", "solvate", "encapsulat".
3) One product per synthesis: Never merge. If the text says “Synthesis of X and Y”, output two lines.
4) Procedure evidence required: The heading or its immediately following paragraph(s) must contain in-paper procedural detail (any of: amounts, solvent names, temperature, time, vessel, pH, workup, isolation) OR an explicit “same as <another synthesis in THIS paper>”. If absent, EXCLUDE.
5) Product concreteness: The product must be a specific instance in THIS paper (unique code/name and/or a concrete formula string and/or an accession identifier such as a CCDC number). Families/archetypes/prototypes without a concrete instance → EXCLUDE.
6) In-paper only: EXCLUDE background or literature-only preparations lacking in-paper procedural detail.
7) Normalization: No LaTeX/TeX commands. Keep plain words like “alpha”. Remove control characters. Normalize whitespace.
8) Different crystal-form qualifiers doesn't mean different synthesis. You should treat them as one synthesis. （XXX-N (something) and (XXX-N (something else)) are the same synthesis.


Polymorph and duplicate control:
- Do NOT split by polymorph, space group, unit cell, crystal system, color, or crystal habit. Only split when the paper describes distinct procedures (different conditions or an explicit second recipe heading).
- Deduplicate by (product code/name, CCDC). If identical, keep one.
- If CCDCs differ but the procedure block is identical and there is no separate recipe heading, treat as ONE synthesis.
- Normalize titles by stripping parenthetical crystal-system/unit-cell qualifiers from the synthesis name.

Decision tests (fail fast, in order):
A) Representability gate: Is the final product a bare MetalOrganicPolyhedron? If YES → proceed. If NO → check precursor exception.
B) Precursor exception: Is it a discrete, isolated 0D precursor cluster synthesized here AND explicitly used in THIS paper to make a MetalOrganicPolyhedron? If YES → proceed. If NO → EXCLUDE.
C) Procedure evidence: In-paper procedural detail or explicit “same as <this paper’s synthesis>”? If NO → EXCLUDE.
D) Composite/adduct filter: Any composite/adduct/host–guest/solvate cue that remains part of the named product? If YES → EXCLUDE.
E) Concreteness: Unique, concrete instance (code/name/formula/identifier) in THIS paper? If NO → EXCLUDE.
F) Polymorph/duplicate control: Apply the rules above to avoid splitting by crystal form and to deduplicate.
G) If all YES → INCLUDE (count distinct routes and interconversions as separate entries).

Output format (plain text, one line per synthesis):
ChemicalSynthesis — <identifier or name of the output from the paper; use the proper product code/name, check through the paper to find proper names, don't use only numbers, without crystal-form qualifiers, short name XXX-Y is preferred for the main name, but also include other names>
Nothing else. 
'''


EXTRACTION_SCOPE_2 = """
TASK
Extract CHEMICAL INPUTS and CHEMICAL OUTPUT. Keep it simple: only include substances explicitly stated as inputs in the described step. Do not infer from product formulas.


CORE RULES
1) INPUTS and OUTPUTS-ONLY: Include a substance only if the text lists it as an input or output in the step.
2) SPLIT MIXTURES: If a mixture is stated as an input (e.g., “A/B”, “A:B = x:y”), output separate ChemicalInputs records for each component.
3) MOP→MOP TRANSFORMATION: For a transformation from pre-isolated MOP a to MOP b, list only MOP a as the ChemicalInputs block.
4) NO BACKFILL: Do not add components solely because they appear in the product name or composition if they were not stated as inputs.
5) Make sure you check the given entity_label and the output name/identifier are the matching exactly. If that went wrong, your entire result will be wrong. You must check multiple times to make sure you choose the correct one. This should be the first step you take, don't proceed unless you are sure you have the correct one.
6) Take your time and make sure you put everything right, revise the result multiple times if necessary.
7) CCDC HANDLING (iter2): Do NOT search for or include CCDC numbers in iter2. Leave the Representation field blank. CCDC resolution is deferred to iter2_1.

FORMULA LOOKUP POLICY
If a formula for any input or product is not stated in the paper, look it up in reliable sources such as PubChem, ChemSpider, or vendor SDS. Annotate provenance as one of:
(as stated)
(looked up: <source or ID>)
(derived: <brief basis>)
Do not invent compositions.

TEXT PARSING
Split mixed media and mixtures into separate candidates. Accept only proper chemical names. Reject placeholders such as atmosphere, solvent, mixture, solution, filtrate, supernatant, or product nicknames.

OUTPUT
Single fenced code block. Structured bullet list. Use these fields and order. Use N/A if not reported.

ChemicalInputs:
- Name: <as written>
- Alternative Names: <semicolon-separated aliases from text or N/A> **Spare no effort to find all aliases mentinoed in the paper (It may appears elsewhere too.), strictly use semicolon as the separator, never comma or any other character**, look up the alias, also look up via external sources. 
- Amount: <as written, include units and mmol if given or N/A>
- Formula: <formula> (<as stated | looked up: <source or ID> | derived: <basis>>)
- Description: <concise functional role such as metal cluster precursor or organic linker>
- Purity: <as written or N/A>
- Supplier: <named vendor | N/A>

Repeat the seven-line ChemicalInputs block for each included input.

ChemicalOutput:
- Identifier: <as written>, usually a short code like name, like XXX-1, XXX-2, etc. **MUST BE THE SAME AS THE GIVEN ENTITY_LABEL"
- Name: <as written for product>
- Formula: <as stated | looked up: <source or ID> | derived: <basis>>
- Representation:  

Put exactly **ONE** ChemicalOutput block for the output. 

FORMATTING RULES
Keep field labels exactly as shown. One blank line between blocks. Do not include JSON, tables, or extra commentary. Split mixed media into separate records. Never emit combined names such as DMF:MeOH.
"""

EXTRACTION_SCOPE_3 = '''
Extract synthesis step TYPES ONLY for the specified entity. Output plain text in this exact format:

Entity: ENTITY_NAME

Steps:
1) StepType1
2) StepType2
3) StepType3

Use only these verbatim step names: Add, Stir, Dissolve, HeatChill, Filter, Transfer, Separate, Dry, Evaporate, Sonicate, Crystallize. Preserve the original sequential order of actions. Treat each distinct action as one step; split multi-action sentences into separate steps. Aim for 5-15 steps, prioritizing high recall for Add and explicit actions to avoid missing steps, especially in the first few. Do not invent, merge, or duplicate steps.

Output ONLY the numbered list of step types. No JSON, no code fences, no explanations, no commentary.

Allowed step types
Add, HeatChill, Evaporate, Sonicate, Dissolve, Crystallize, Transfer, Separate, Filter, Dry, Stir.

Golden typing rules (strict)
- ADD (high recall):
  - Use for any addition of reagents, solvents, or mixtures (e.g., "added X to Y", "suspended in solvent").
  - Split lists (e.g., "A, B, and C" → multiple Add steps, keep text order).
  - If a mixture is stated (e.g., "DMF/MeOH (v/v=n:m)" or "a mixture of A and B"), emit separate Add for each component; do NOT also Add the combined label.
  - Default to Add when ambiguous vs Dissolve or Transfer.
  - Do NOT emit Add for vessels/equipment/operations (e.g., "placed in vial", "sealed in reactor", "loaded into autoclave"). Use Transfer only when an explicit transfer verb is present.

- DISSOLVE (ultra-strict gate):
  - Emit ONLY when an explicit dissolution verb appears AND a solute is identified, e.g.,
    • "dissolve|dissolved|dissolving <solute> in/with <solvent>"
    • "prepared a solution of <solute> in <solvent>"
    • "stock solution of <solute> in <solvent> was prepared"
    • "suspend|suspended <solid> in <solvent>"
  - If no explicit dissolution verb appears, do NOT emit Dissolve. Use Add for the solvent(s) instead.
  - If a sentence says "a solution of X in Y was added" and no preparation step is described here, emit Add (substance="solution of X in Y"); do not create a Dissolve.
  - When valid, list each solvent/ratio in Dissolve parameters; do not also create Add for those solvents.
  - Do not infer Stir from "dissolved" unless "stir" is explicit.

- STIR: Never a separate step. When agitation is explicit, set stirring_status=true on the relevant operational step.

- HEATChill:
  - One step for a continuous heat-and-hold (use target_temperature and duration together).
  - Cooling is a separate HeatChill when stated; include temperature or "room temperature" when present.
  - If "heated then cooled" appears, create two HeatChill steps.

- TRANSFER (strict gate):
  - Emit ONLY for explicit verbs: transfer/transferred/transferring/pour/decant/pipette/aliquot/load/charge into another vessel.
  - "added to flask", "poured into" used to introduce inputs → classify as Add if introducing materials; otherwise ignore.

- SEPARATE: Explicit phase separation/extraction terms only (e.g., separate/decant/extract/liquid–liquid).

- FILTER (high recall):
  - Emit for filter/filtered/filtration or clear isolation of solids.
  - Include washes (e.g., "washed with X") in a single Filter step (washing_solvent parameter). Never emit Add for wash solvents.
  - Do not create multiple Filters for sequential washes; keep one with all washing solvents.

- DRY: Emit for explicit drying (e.g., "dried under vacuum/air", "oven-dried").

- EVAPORATE: Emit for explicit evaporation/concentration (e.g., "evaporated to dryness", "solvent removed under reduced pressure").

- CRYSTALLIZE (strict):
  - Emit only if a crystallization verb is present AND at least one operating detail (method/time/temperature). Outcome-only phrases are not Crystallize.

VESSEL TRACKING (critical)
- Track which vessel each step uses. If the paper mentions named vessels (e.g., vial 1, Parr autoclave), maintain that assignment.
- Every step MUST have a vessel_name. If not explicit, inherit from the previous step.
- Transfers between containers increment vessel ids (Vessel 1 → Vessel 2, etc.). Do not renumber later.

Atmosphere and agitation
- Capped vial ≠ sealed. If only capped, set vessel_environment="air", sealed_status=false, underVacuum=false.
- Do not infer inert or vacuum unless explicit.
- Stirring is modeled via stirring_status on the relevant step; do not create standalone Stir steps.

STRICT COUNTS
- The number of Add steps equals the number of distinct materials explicitly added.
- For multi-solvent phrases like "in DMF/MeOH (v/v=…)": use Dissolve only if the Dissolve gate is met; otherwise, emit separate Add steps for each solvent.
- No Separate or Transfer without trigger verbs.
- Exactly one heating HeatChill per continuous heating profile.

STRICT RULE
For every input for the synthesis, you add a separate "Add". Here "input" means chemical substances only (reagents, solvents, solutions/mixtures). Do not treat vessels, caps, seals, atmospheres, or equipment as inputs.

Output format (plain text only)
Entity: <exact entity_label>

Steps:
1) <step_type>
2) <step_type>
3) <step_type>

Output ONLY the numbered list. No JSON, no code fences, no explanations.
'''


EXTRACTION_SCOPE_3_1 = '''
Goal
Extract all operational step DETAILS for one specified ChemicalSynthesis, using the step types from iter3 as a guide. Preserve order. Output plain text only (no JSON, no code fences, no explanations).


Scope
- Top entity: ChemicalSynthesis only. Exclude other syntheses, ligand prep, workups, characterization.
- Steps are actions only. Names, yields, formulas, narrative are not steps.
- Use the step types provided from iter3 as authoritative guidance for which steps to extract.

Allowed step types
Add, HeatChill, Evaporate, Sonicate, Dissolve, Crystallize, Transfer, Separate, Filter, Dry, Stir.

VESSEL TRACKING (critical)
- Track which vessel each step uses. If the paper mentions named vessels (e.g., vial 1, Parr autoclave), maintain that assignment.
- Every step MUST have a vessel_name. If not explicit, inherit from the previous step.
- Transfers between containers increment vessel ids (Vessel 1 → Vessel 2, etc.). Do not renumber later.

Atmosphere and agitation
- Capped vial ≠ sealed. If only capped, set vessel_environment="air", sealed_status=false, underVacuum=false.
- Do not infer inert or vacuum unless explicit.
- Stirring is modeled via stirring_status on the relevant step; do not create standalone Stir steps.

Required fields per step (emit all if stated; use "not stated" if missing)
- step_type (one of the allowed step types, matching iter3 guidance)
- order (1..N, contiguous, matching iter3 order)
- synthesis_label (exact entity_label)
- vessel_name (Vessel 1, Vessel 2, … or explicit name)
- vessel_environment (Air/Nitrogen/Argon/etc. or "not stated")
- duration (e.g., "12 h" or "not stated")
- equipment (device name/brand/model if given; else "not stated")
- parameters (only schema keys for that step type; omit irrelevant keys)

Parameter schema (only these keys under parameters)
- HeatChill: target_temperature, temperature_rate, pressure_or_vacuum, sealed_status, stirring_status, device
- Add: substance, amount_or_concentration, target_pH, layered_status, stirring_status
- Evaporate: temperature, pressure, device, to_volume, removed_species
- Dry: drying_agent, temperature, pressure, method
- Filter: medium_or_method, washing_solvent, repeated_status, vacuum_filtration
- Transfer: from_vessel, to_vessel, transferred_amount, layered_transfer
- Separate: separation_type, solvent_or_phase
- Dissolve: solvent, concentration_or_ratio, temperature
- Crystallize: target_temperature, method
- Stir: stirring_speed, temperature (if applicable)

Output format (plain text; no JSON, no tables, no code fences)
- First line: ChemicalSynthesis — <exact label of this procedure>
- Then a section "Steps:" with one line per step as:
  <order>) <step_type> | vessel_name: <...> | vessel_environment: <...> | duration: <...> | equipment: <...> | parameters: <key>=<value>; <key>=<value>
- Keep the exact wording from the paper where applicable; normalize whitespace only.
- Match the step count and order from iter3 guidance.
'''


EXTRACTION_SCOPE_4 = '''

Goal
Extract information for one specified ChemicalSynthesis only.

Top-level and scope
- Top-level entity type: ChemicalSynthesis.
- Work on this single procedure only. Do not include information from other procedures.
- Strictly only extract information for the given entity_label. 

Prior iteration context
- If iter3 step hints for this entity are provided in the input context, treat them as authoritative for vessel assignment and step ordering. Do not re-derive steps; reuse vessels and atmospheres consistently.
- Equipment-to-step mapping: When outputting Equipment, explicitly map each item to the vessel_name(s) and the iter3 step order(s) where it is used. Use the format "Vessel <N> — <equipment descriptor> (steps: <orders>)". If an item is not tied to a specific vessel (e.g., an oven for drying), omit the vessel prefix and include only the step order(s).

What to extract
1) Yield
   - Extract every explicit yield percentage reported for this procedure.
   - Record the numeric value(s) as written and any explicit qualifiers (e.g., “isolated yield”, “crystalline yield”, “overall yield”, “based on <reagent>”) if present.
   - If multiple yields are given for the same product run, list each with its qualifier.
   - Do not calculate yields from masses or moles. If no percentage is stated, write “not stated”.

2) Equipment
   - Extract all process equipment explicitly used in this procedure, including vessels and heat/chill devices.
   - Include exact names and descriptors as written (e.g., material, volume, model, brand).
   - Include ancillary process equipment if explicitly used (e.g., autoclave, oven, ultrasonic bath, centrifuge, vacuum setup).
   - Exclude analytical/characterization instruments not part of the synthesis operation (e.g., NMR, IR, PXRD).
   - Use the vessel_name values and numbering from iter3 step hints (e.g., 'Vessel 1', 'Vessel 2'). Do not renumber vessels in iter4.
   - For each equipment entry, include the vessel_name (when applicable) and the iter3 step order(s) where it is used in the format: "(steps: <orders>)". Compress contiguous step ranges where appropriate (e.g., "1–3, 6").
   - If an equipment item spans multiple vessels, emit separate lines per vessel with the corresponding step range(s).
   - For non-vessel-bound devices (e.g., oven, vacuum setup) that operate across the procedure, omit vessel_name and include only step order(s).

All fields are compulsory for every step.

**Critical**: Vessel 1, 2 refers to the synthesis mentioned in the paper, e.g.,  for the first synthesis discussed in the paper, by 
default, we use 'vessel 1' if this synthesis uses the same vessel across the steps, then for the second synthesis, we use 'vessel 2', etc.

3) Source links
   - Extract explicit links to the source document context for this procedure: section titles, subsection titles, paragraph labels or numbers, or other in-document anchors.
   - If the document provides no explicit context labels, write “not stated”.

Evidence and inheritance
- Use only facts stated for this procedure in this paper.
- If the text says same as / identical to / following / according to / similar to / akin to another procedure in this paper:
  - You may inherit equipment only if the equipment is explicitly implied to be the same.
  - Do not inherit yield unless a yield for this specific procedure is explicitly stated.
  - Mark inherited equipment entries with “inherited from <label>”.
  - Do not inherit across papers.

Normalization
- Preserve author wording; normalize whitespace; remove control characters.
- Do not use LaTeX/TeX notation.
- Do not use romanized Greek words; use Unicode Greek symbols and plain text only.
- Do not invent or infer percentages, equipment, suppliers, or contexts.

Output format (plain text, no JSON, no examples)
- First line: ChemicalSynthesis — <exact label of this procedure>
- Then a section “Yield:” listing the percentage value(s) with any qualifiers, or “not stated”.
- Then a section “Equipment:” one item per line, mapping each item to vessel_name and step order(s) as available, using: "Vessel <N> — <descriptor> (steps: <orders>)" or "<descriptor> (steps: <orders>)" if no vessel applies; include vessels and heat/chill devices; mark inherited items as specified.
- Then a section “Source links:” listing the exact section/paragraph labels or “not stated”.
'''
 

# Pre-extraction of raw relevant text spans (used before step extraction)
EXTRACTION_SCOPE_6_PRE_EXTRACTION = """
Extract the ORIGINAL TEXT spans from the paper that describe the procedure for the specified entity only.

Special handling for transformations: If the entity_label indicates a transformation/conversion/exchange/activation/post-synthetic modification/treatment (e.g., "transformation VMOP-α to VMOP-β"), extract ONLY the transformation procedure itself (the steps that convert material A to material B). Do NOT trace back to or include the original synthesis of the starting material.

Core rules:
- Strictly include only content relevant to the entity_label's procedure; exclude other entities or unrelated sections.
- Aggregate all relevant snippets even if scattered across the paper; preserve original wording verbatim.
- Preserve order as they appear in the paper; separate non-contiguous snippets with a blank line.
- Do NOT summarize or paraphrase; return only the raw text excerpts. Output ONLY the text (no commentary, no code fences, no JSON).

Reference resolution (for non-transformations):
- If the text contains vague references (e.g., "above-mentioned procedure", "same method as", "similar to the synthesis of", "prepared as described for", "following the procedure"), you MUST:
  1) First include the original sentence with the reference
  2) Then add a clear separator line: The "[referenced phrase]" refers to the following content:
  3) Then include the FULL referenced synthesis text

Entity: ENTITY_NAME
Paper:
<<<
[INSERT_PAPER_TEXT_HERE]
>>>

Output ONLY the raw text excerpts (no commentary, no code fences, no JSON).
"""
