# Auto-generated by spec_generation.py

MCP_PROMPT_ITER_1 = '''Follow these generic rules for any iteration.

Identification:
- If a DOI is provided by upstream context, treat it as the sole task identifier and reuse it consistently. Do not invent new identifiers.
Don't change any details of the doi.

The following is the doi: {doi}

Entity focus:

- When entity_label and entity_uri are provided, scope all creation and connections to this entity. You may create and connect new entities only insofar as they attach to this scoped entity.

Task-specific rules for this iteration come after this header.


==============

Using only the extracted information, create instances of ontosyn:ChemicalSynthesis for each chemical synthesis procedure described. For each, create a single ontosyn:ChemicalOutput instance and link it using ontosyn:hasChemicalOutput. If the chemical output is represented by a MetalOrganicPolyhedron, link it using ontosyn:isRepresentedBy. Link each ChemicalSynthesis to its source document using ontosyn:retrievedFrom. Write all triples to output.ttl.

==============

The following is the paper content for your task: 

{paper_content}'''

MCP_PROMPT_ITER_2 = '''Follow these generic rules for any iteration.

Identification:
- If a DOI is provided by upstream context, treat it as the sole task identifier and reuse it consistently. Do not invent new identifiers.
Don't change any details of the doi.

The following is the doi: {doi}

Entity focus:

- When entity_label and entity_uri are provided, scope all creation and connections to this entity. You may create and connect new entities only insofar as they attach to this scoped entity.

Task-specific rules for this iteration come after this header.


==============

Using only the extracted information, for each ontosyn:ChemicalInput identified, create an instance and link it to the corresponding ontosyn:ChemicalSynthesis using ontosyn:hasChemicalInput. For each chemical input, add all alternative names (ontosyn:hasAlternativeNames), chemical formula (ontosyn:hasChemicalFormula), detailed description (ontosyn:hasChemicalDescription), purity (ontosyn:hasPurity), and supplier (ontosyn:isSuppliedBy) if explicitly mentioned. If a reference to an external material is provided, link using ontosyn:referencesMaterial. Write all triples to output.ttl.

==============


This is the top level entity for you to focus on during this iteration. 
{entity_label}, {entity_uri}

The following is the paper content for your task: 

{paper_content}'''

MCP_PROMPT_ITER_3 = '''Follow these generic rules for any iteration.

Identification:
- If a DOI is provided by upstream context, treat it as the sole task identifier and reuse it consistently. Do not invent new identifiers.
Don't change any details of the doi.

The following is the doi: {doi}

Entity focus:

- When entity_label and entity_uri are provided, scope all creation and connections to this entity. You may create and connect new entities only insofar as they attach to this scoped entity.

Task-specific rules for this iteration come after this header.


==============

Using only the extracted information, for each synthesis step in each ontosyn:ChemicalSynthesis, create an instance of the appropriate step class (from Add, Stir, HeatChill, Evaporate, Sonicate, Dissolve, Crystallize, Transfer, Separate, Filter, Dry, SeparationType). Link each step to its parent ChemicalSynthesis using ontosyn:hasSynthesisStep. For each step, set ontosyn:hasOrder, and add all step-specific properties as described in the T-Box (including vessels, vessel environments, duration, equipment, and all step-type-specific parameters). Ensure all connections and properties are created in this iteration. Write all triples to output.ttl.

==============


This is the top level entity for you to focus on during this iteration. 
{entity_label}, {entity_uri}

The following is the paper content for your task: 

{paper_content}'''

MCP_PROMPT_ITER_4 = '''Follow these generic rules for any iteration.

Identification:
- If a DOI is provided by upstream context, treat it as the sole task identifier and reuse it consistently. Do not invent new identifiers.
Don't change any details of the doi.

The following is the doi: {doi}

Entity focus:

- When entity_label and entity_uri are provided, scope all creation and connections to this entity. You may create and connect new entities only insofar as they attach to this scoped entity.

Task-specific rules for this iteration come after this header.


==============

Using only the extracted information, for each ontosyn:ChemicalSynthesis, add the yield using ontosyn:hasYield, and link all equipment used (ontosyn:hasEquipment). Ensure all explicit links to the source document are included using ontosyn:retrievedFrom. Write all triples to output.ttl.

==============


This is the top level entity for you to focus on during this iteration. 
{entity_label}, {entity_uri}

The following is the paper content for your task: 

{paper_content}'''

