[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp_tool_layer"
version = "0.0.1"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]