TASK_GROUP_REFINEMENT_DESCRIPTION = """
    This tool is used to output the refined task group. 
    The input is a list of Task objects. 
    The output is a string indicating the file path where the refined task group is output. 

    Args:
        refined_task_group: the refined task group, which is a list of Task objects.
        meta_task_name: the name of the meta task, which is a string.
        iteration_index: the iteration index of the task, which is an integer.

    Returns:
        The file path where the refined task group is output. 


    Here is the breakdown of the tool object:
        Tool object: 
            - name: the name of the tool, which is a string. 
            - description: the description of the tool, which is a string. 
            - is_llm: whether the tool is purely LLM generation of content, which is a boolean. 
            - exists: whether the tool exists in the mcp tools, which is a boolean. For hypothetical tools, set this to False. 

    Here is the breakdown of the task object:
        Task object: 
            - task_id: the task id, which is a string. 
            - name: the name of the task, which is a string. 
            - description: the description of the task, which is a string. 
            - tools_required: the tools required for the task, which is a list of Tool objects. 
            - task_dependencies: the task dependencies, which is the task ids of tasks that must be completed before this task can be started, which is a list of strings. 
            - output_files: the files and their relative paths that should be generated by the task, which is a list of strings. (usually should be in sandbox/data repository). 
            The output files should only include file related to the task. 
            - required_inputs: the files that are required for the task, which is a list of strings. 
    """


TASK_REFINEMENT_DESCRIPTION = """
    This tool is for outputing detailed updated task files.  

    - task_id: the task id remains the same as the old task. 
    - name: the name remains the same as the old task. 
    - description: a detailed description of the task, which is a string. 
    - tools_required: the tools required for the task, which is a list of Tool objects. If the task requires LLM generation of content, e.g., creating a ttl file, writing a report, include 
    "llm" in the list.
    - task_dependencies: remains the same as the old task. Make sure you put the task id of the parent tasks in the list. 
    - output_files: the files and their relative paths that should be generated by the task, which is a list of strings. (usually should be in sandbox/data repository). 
    The output files should only include file related to the task. 


        Tool object: 
            - name: the name of the tool, which is a string. 
            - description: the description of the tool, which is a string. 
            - is_llm: whether the tool is LLM generation of content, which is a boolean. 
            - exists: whether the tool exists in the mcp tools, which is a boolean. For hypothetical tools, set this to False. 

    Args:
        new_task: the input for the task, which is a AddDetailedTaskInput object.
        iteration_index: the iteration index of the task, which is an integer provided in the prompt.
        meta_task_name: the name of the meta task, which is a string provided in the prompt.
    Returns:
        The file path where the new task is created. 
    """

RESOURCE_REGISTRATION_DESCRIPTION = """
    This tool is used to register the resources found in the data folder. 

    The input is a list of ResourceRegistrationInput objects. 

    - resource_name: The name of the resource.
    - resource_type: The type of the resource.
    - resource_description: The description of the resource.
    - resource_location: The location of the resource.

    The output is a string indicating the file path where the resource registration report is output. 

    """