PREFIX mofs: <https://www.theworldavatar.com/kg/ontomofs_vkg/>
SELECT ?mofid ?pld ?lcd ?co2_uptake
WHERE {
  ?mof a mofs:MetalOrganicFramework ;
       mofs:hasMofidV1 ?mofid ;
       mofs:hasSourcedb "Tobassco" ;
       mofs:hasPredAdsorptionUptake_CO2P15T298mmolg ?co2_uptake ;
       mofs:hasPLD ?pld ;
       mofs:hasLCD ?lcd .
  FILTER(?pld >= 10 && ?co2_uptake < 300)
}
ORDER BY DESC(?co2_uptake)
LIMIT 10
