PREFIX mofs: <https://www.theworldavatar.com/kg/ontomofs_vkg/>
SELECT (AVG(?co2) AS ?avg_co2) (MIN(?co2) AS ?min_co2) (MAX(?co2) AS ?max_co2)
WHERE {
  ?mof a mofs:MetalOrganicFramework ;
       mofs:hasSourcedb "Tobassco" ;
       mofs:hasPredAdsorptionUptake_CO2P15T298mmolg ?co2 .
}
