"""
BaseAgent – a reusable ReAct-based agent that can load one or more MCP
tools and keep their sessions alive for the whole run.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
from contextlib import AsyncExitStack
from pathlib import Path
from typing import Any, Dict, List, Mapping, Tuple
from uuid import uuid4
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.prebuilt import create_react_agent
from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain_mcp_adapters.prompts import load_mcp_prompt
from langchain_mcp_adapters.tools import load_mcp_tools

from models.LLMCreator import LLMCreator
from models.MCPConfig import MCPConfig
from models.ModelConfig import ModelConfig
from models.TokenCalculator import TokenCounter
from models.llm_call_telemetry import journal_path, summarize_costs, telemetry_context
from src.utils.global_logger import get_logger


_PIPELINE_OWNED_MCP_ENV = {
    "TWA_AGENTIC_DATA_DIR",
    "TWA_CENTRAL_MEMORY_DIR",
    "TWA_GENERATED_ARTIFACT_ROOT",
}


def _merge_mcp_server_environment(
    configured_env: Dict[str, Any],
    inherited_env: Dict[str, Any],
) -> Dict[str, Any]:
    """Merge MCP env while preserving pipeline-owned runtime locations."""
    merged = dict(inherited_env)
    for key, value in configured_env.items():
        if key in _PIPELINE_OWNED_MCP_ENV and key in inherited_env:
            continue
        text = str(value)
        if text.startswith("${") and text.endswith("}") and len(text) > 3:
            env_key = text[2:-1]
            if env_key in inherited_env:
                merged[key] = inherited_env[env_key]
            continue
        merged[key] = value
    return merged


def _flatten_exception_group(exc: BaseException) -> List[BaseException]:
    """Flatten Python/AnyIO exception groups into actionable leaf exceptions."""
    children = getattr(exc, "exceptions", None)
    if not children:
        return [exc]
    leaves: List[BaseException] = []
    for child in children:
        leaves.extend(_flatten_exception_group(child))
    return leaves


def exception_details(exc: BaseException) -> List[Dict[str, str]]:
    """Return serializable leaf causes from ordinary and grouped exceptions."""
    return [
        {"type": type(item).__name__, "message": str(item)}
        for item in _flatten_exception_group(exc)
    ]


def compose_user_message_with_mcp_instruction(
    *,
    task_instruction: str,
    mcp_instruction: str,
    task_continuation: str = "",
) -> str:
    """Assemble the user-aligned ONEPASS message in Legacy order.

    Pipeline supplies only case bindings and later runtime extras. This helper
    inserts the MCP ``instruction`` prompt between them so the live user
    message is ``bindings + contract + extras`` with no placeholder slot.
    Callers own all separators; the binding envelope already ends with a blank
    line so concatenation matches the unbound Legacy template.
    """
    return f"{task_instruction}{mcp_instruction}{task_continuation}"


def _compact_receipt_value(value: Any) -> Any:
    """Keep decision-relevant values; hash long committed payloads for audit."""
    if isinstance(value, dict):
        return {
            str(key): _compact_receipt_value(item)
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [_compact_receipt_value(item) for item in value]
    if isinstance(value, str) and len(value) > 240:
        return {
            "preview": value[:160],
            "sha256": hashlib.sha256(value.encode("utf-8")).hexdigest(),
            "length": len(value),
        }
    return value


def _canonical_args_sha256(args: Mapping[str, Any]) -> str:
    canonical = json.dumps(
        dict(args),
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _canonical_semantic_identity(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            str(key): _canonical_semantic_identity(item)
            for key, item in sorted(value.items())
        }
    if isinstance(value, (list, tuple)):
        return [_canonical_semantic_identity(item) for item in value]
    if isinstance(value, str):
        return " ".join(value.casefold().split())
    return value


def _semantic_call_fingerprint(
    call: Mapping[str, Any],
    identity_index: Mapping[str, tuple[str, ...]],
) -> str:
    """Match the fingerprint generated by occurrence wrappers before execution."""
    name = str(call.get("name") or "").strip()
    identity_keys = identity_index.get(name)
    args = call.get("args") or call.get("arguments") or {}
    if not name or not identity_keys or not isinstance(args, Mapping):
        return ""
    identity: dict[str, Any] = {}
    for key in identity_keys:
        if key not in args or args[key] is None or str(args[key]).strip() == "":
            return ""
        identity[key] = args[key]
    canonical = json.dumps(
        {
            "tool": name,
            "identity": _canonical_semantic_identity(identity),
        },
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _looks_like_argument_validation_error(
    content: str,
    payload: Mapping[str, Any] | None = None,
) -> bool:
    combined = " ".join(
        [
            str(content or ""),
            json.dumps(dict(payload or {}), ensure_ascii=False, default=str),
        ]
    ).casefold()
    markers = (
        "validationerror",
        "validation error",
        "unexpected keyword",
        "unexpected_keyword_argument",
        "extra_forbidden",
        "missing required argument",
        "field required",
        "input should be",
        "pydantic",
    )
    return any(marker in combined for marker in markers)


def _normalized_tool_error_payload(
    *,
    content: str,
    status: str,
    call: Mapping[str, Any] | None = None,
    identity_index: Mapping[str, tuple[str, ...]] | None = None,
    parsed: Any = None,
    classify_argument_owner_mismatch: bool = False,
) -> dict[str, Any] | None:
    """Normalize FastMCP/Pydantic errors for ReAct history and pipeline audit."""
    payload = dict(parsed) if isinstance(parsed, Mapping) else {}
    is_error = str(status or "").casefold() == "error" or payload.get("ok") is False
    if not is_error:
        return payload if payload else None
    validation = _looks_like_argument_validation_error(content, payload)
    if not payload:
        payload = {"message": str(content or "")[:2000]}
    payload.setdefault("status", "error")
    payload.setdefault(
        "code",
        "TOOL_ARGUMENT_VALIDATION" if validation else "TOOL_EXECUTION_ERROR",
    )
    payload.setdefault("ok", False)
    if validation:
        payload.setdefault("graph_changed", False)
        payload.setdefault("pre_execution_error", True)
        payload.setdefault("retryable", True)
        call_name = str((call or {}).get("name") or "").strip()
        call_args = (call or {}).get("args") or (call or {}).get("arguments") or {}
        allowed_by_tool, owners_by_argument = _argument_contract_indexes()
        allowed = allowed_by_tool.get(call_name) or set()
        invalid_arguments = sorted(
            str(key)
            for key in call_args
            if allowed and str(key) not in allowed
        )
        if allowed:
            payload.setdefault("tool_name", call_name)
            payload.setdefault("allowed_arguments", sorted(allowed))
        if invalid_arguments:
            payload.setdefault("invalid_arguments", invalid_arguments)
            argument_owners = {
                argument: [
                    owner
                    for owner in owners_by_argument.get(argument, [])
                    if owner != call_name
                ]
                for argument in invalid_arguments
            }
            payload.setdefault("argument_owners", argument_owners)
            text = " ".join(
                (
                    str(content or ""),
                    json.dumps(payload, ensure_ascii=False, default=str),
                )
            ).casefold()
            extra_only = (
                (
                    "unexpected keyword" in text
                    or "unexpected_keyword_argument" in text
                    or "extra_forbidden" in text
                )
                and "field required" not in text
                and "missing required argument" not in text
                and "input should be" not in text
            )
            payload.setdefault(
                "auto_repairable_extra_arguments",
                bool(extra_only and not classify_argument_owner_mismatch),
            )
            if (
                classify_argument_owner_mismatch
                and any(argument_owners.values())
            ):
                payload["code"] = "ARGUMENT_OWNER_MISMATCH"
                payload["auto_repairable_extra_arguments"] = False
                payload["recovery"] = {
                    "action": "retry_original_and_route_supported_owner",
                    "instruction": (
                        "The call was not executed. Retry the original occurrence "
                        "without fields owned by other tools. Call an indicated owner "
                        "tool separately only when the source ledger independently "
                        "supports that occurrence; otherwise do not invent it."
                    ),
                }
            else:
                payload.setdefault(
                    "recovery",
                    {
                        "action": "retry_without_invalid_arguments",
                        "instruction": (
                            "Retry the original tool once without the invalid "
                            "arguments. Route removed fields to another owner tool "
                            "only when the ledger independently supports that "
                            "occurrence."
                        ),
                    },
                )
        fingerprint = _semantic_call_fingerprint(
            call or {},
            identity_index or {},
        )
        if fingerprint:
            payload.setdefault("semantic_fingerprint", fingerprint)
    return payload


def project_react_history_to_receipts(
    state: Dict[str, Any],
    *,
    classify_argument_owner_mismatch: bool = False,
) -> Dict[str, Any]:
    """Project completed tool turns without mutating the full trace state.

    The model keeps the original task, compact committed-operation receipts, and
    any unresolved/recent non-tool messages. Full AI/Tool messages remain in the
    graph state and therefore in the final trace.
    """
    messages = list(state.get("messages") or [])
    if len(messages) < 3:
        return {"llm_input_messages": messages}
    identity_index = _loop_guard_identity_index(
        load_occurrence_loop_guard_contract()
    )

    output_by_id: Dict[str, ToolMessage] = {}
    for message in messages:
        if isinstance(message, ToolMessage):
            call_id = str(getattr(message, "tool_call_id", "") or "")
            if call_id:
                output_by_id[call_id] = message

    completed_ai_ids: set[int] = set()
    completed_tool_ids: set[str] = set()
    receipts: List[Dict[str, Any]] = []
    for index, message in enumerate(messages):
        if not isinstance(message, AIMessage):
            continue
        calls = list(getattr(message, "tool_calls", []) or [])
        if not calls:
            continue
        call_ids = [str((call or {}).get("id") or "") for call in calls]
        if not call_ids or any(call_id not in output_by_id for call_id in call_ids):
            continue
        completed_ai_ids.add(index)
        for call, call_id in zip(calls, call_ids):
            output = output_by_id[call_id]
            completed_tool_ids.add(call_id)
            content = _normalize_ai_message_content(
                getattr(output, "content", None)
            )
            try:
                parsed_output: Any = json.loads(content)
            except Exception:
                parsed_output = None
            parsed_output = _normalized_tool_error_payload(
                content=content,
                status=str(getattr(output, "status", "") or ""),
                call=call or {},
                identity_index=identity_index,
                parsed=parsed_output,
                classify_argument_owner_mismatch=(
                    classify_argument_owner_mismatch
                ),
            ) or {"message": content[:1000]}
            if isinstance(parsed_output, dict):
                retained_output = {
                    key: parsed_output[key]
                    for key in (
                        "status",
                        "code",
                        "message",
                        "iri",
                        "dependent_iri",
                        "quantity_iri",
                        "object_iri",
                        "reused",
                        "already_committed",
                        "graph_changed",
                        "graph_revision",
                        "semantic_fingerprint",
                        "fingerprint",
                        "facet_warnings",
                        "omitted_facet",
                        "conflicts",
                    )
                    if key in parsed_output
                }
                if str(parsed_output.get("status", "")).lower() != "ok":
                    retained_output["error_details"] = _compact_receipt_value(
                        parsed_output
                    )
            else:
                retained_output = {"result": _compact_receipt_value(parsed_output)}
            firewall_payload = (
                getattr(message, "additional_kwargs", {}) or {}
            ).get("argument_firewall")
            if isinstance(firewall_payload, Mapping):
                matching_warning = next(
                    (
                        dict(item)
                        for item in firewall_payload.get("warnings") or []
                        if isinstance(item, Mapping)
                        and str(item.get("call_id") or "") == call_id
                    ),
                    None,
                )
                if matching_warning:
                    retained_output["argument_firewall_warning"] = matching_warning
            args = dict((call or {}).get("args") or {})
            args_sha256 = _canonical_args_sha256(args)
            status = str(retained_output.get("status") or "").lower()
            if status == "ok":
                operation = str((call or {}).get("name") or "")
                identity_keys = identity_index.get(operation)
                if identity_keys:
                    receipt_args = {
                        key: _compact_receipt_value(args[key])
                        for key in identity_keys
                        if key in args
                    }
                else:
                    receipt_args = {"args_fingerprint": args_sha256}
                receipt_args["supplied_facets"] = sorted(
                    key
                    for key, value in args.items()
                    if key not in (identity_keys or ()) and value is not None
                )
            else:
                receipt_args = _compact_receipt_value(args)
            receipts.append(
                {
                    "operation": str((call or {}).get("name") or ""),
                    "args": receipt_args,
                    "args_sha256": args_sha256,
                    "result": retained_output,
                }
            )

    if not receipts:
        return {"llm_input_messages": messages}

    projected: List[Any] = []
    first_human_kept = False
    for index, message in enumerate(messages):
        if isinstance(message, HumanMessage) and not first_human_kept:
            projected.append(message)
            first_human_kept = True
            continue
        if index in completed_ai_ids:
            continue
        if isinstance(message, ToolMessage):
            call_id = str(getattr(message, "tool_call_id", "") or "")
            if call_id in completed_tool_ids:
                continue
        projected.append(message)

    deduplicated: Dict[str, Dict[str, Any]] = {}
    for receipt in receipts:
        result = receipt.get("result") or {}
        semantic_fingerprint = (
            result.get("semantic_fingerprint") or result.get("fingerprint")
            if isinstance(result, Mapping)
            else None
        )
        key = json.dumps(
            (
                {
                    "operation": receipt.get("operation"),
                    "semantic_fingerprint": semantic_fingerprint,
                    # Contract identity remains a safety boundary even if a
                    # server accidentally reuses a semantic fingerprint.
                    "identity_args": {
                        name: value
                        for name, value in dict(receipt.get("args") or {}).items()
                        if name != "supplied_facets"
                    },
                }
                if semantic_fingerprint
                else {
                    "operation": receipt.get("operation"),
                    "args_sha256": receipt.get("args_sha256"),
                }
            ),
            ensure_ascii=False,
            sort_keys=True,
        )
        if key in deduplicated:
            deduplicated[key]["repeat_count"] = (
                int(deduplicated[key].get("repeat_count") or 1) + 1
            )
            deduplicated[key]["result"] = receipt.get("result")
        else:
            deduplicated[key] = dict(receipt)
            deduplicated[key]["repeat_count"] = 1
    receipt_text = (
        "AUTHORITATIVE MCP STATE: each status=ok receipt below has committed its "
        "owner. Do not recreate a committed owner. If omitted_facet=true, retry that "
        "same occurrence identity only with the corrected omitted facet; the MCP will "
        "enrich the existing owner. Otherwise continue only with ledger headings that "
        "have no successful receipt. Use returned IRIs where needed. Full raw calls "
        "remain in the audit trace.\n"
        + "\n".join(
            json.dumps(receipt, ensure_ascii=False, sort_keys=True)
            for receipt in deduplicated.values()
        )
    )
    insert_at = 1 if projected and isinstance(projected[0], HumanMessage) else 0
    projected.insert(insert_at, SystemMessage(content=receipt_text))
    return {"llm_input_messages": projected}


_V4_FALLBACK_LOOP_GUARD = {
    "schema_version": "occurrence-loop-guard.v1",
    "unique_parent_tools": [
        {
            "name": "create_synthesis_output",
            "identity_args": ["synthesis_iri"],
        }
    ],
    "ordered_member_tools": [],
}
_LOOP_GUARD_CACHE: tuple[str, float, dict[str, Any]] | None = None
_ARGUMENT_OWNERSHIP_CACHE: tuple[str, float, dict[str, Any]] | None = None


def _loop_guard_contract_path() -> Path | None:
    root = str(os.environ.get("TWA_GENERATED_ARTIFACT_ROOT") or "").strip()
    if not root:
        return None
    ontology = str(os.environ.get("TWA_MAIN_ONTOLOGY_NAME") or "ontosynthesis").strip()
    if not ontology:
        ontology = "ontosynthesis"
    path = Path(root) / "scripts" / ontology / "_occurrence_loop_guard.json"
    return path if path.is_file() else None


def load_occurrence_loop_guard_contract() -> dict[str, Any]:
    """Load the compiled loop-guard contract, or the v4 fallback when absent."""
    global _LOOP_GUARD_CACHE
    path = _loop_guard_contract_path()
    if path is None:
        return dict(_V4_FALLBACK_LOOP_GUARD)
    mtime = path.stat().st_mtime
    cache = _LOOP_GUARD_CACHE
    if cache is not None and cache[0] == str(path) and cache[1] == mtime:
        return dict(cache[2])
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        return dict(_V4_FALLBACK_LOOP_GUARD)
    _LOOP_GUARD_CACHE = (str(path), mtime, payload)
    return dict(payload)


def load_occurrence_argument_ownership_contract() -> dict[str, Any]:
    """Load generated allowed arguments and nested ownership metadata."""
    global _ARGUMENT_OWNERSHIP_CACHE
    root = str(os.environ.get("TWA_GENERATED_ARTIFACT_ROOT") or "").strip()
    if not root:
        return {}
    ontology = str(
        os.environ.get("TWA_MAIN_ONTOLOGY_NAME") or "ontosynthesis"
    ).strip() or "ontosynthesis"
    path = (
        Path(root)
        / "scripts"
        / ontology
        / "_occurrence_argument_ownership.json"
    )
    if not path.is_file():
        return {}
    mtime = path.stat().st_mtime
    cache = _ARGUMENT_OWNERSHIP_CACHE
    if cache is not None and cache[0] == str(path) and cache[1] == mtime:
        return dict(cache[2])
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        return {}
    _ARGUMENT_OWNERSHIP_CACHE = (str(path), mtime, payload)
    return dict(payload)


def _argument_contract_indexes() -> tuple[
    dict[str, set[str]],
    dict[str, list[str]],
]:
    by_tool: dict[str, set[str]] = {}
    owners: dict[str, list[str]] = {}
    payload = load_occurrence_argument_ownership_contract()
    for raw in payload.get("tools") or []:
        if not isinstance(raw, Mapping):
            continue
        name = str(raw.get("name") or "").strip()
        allowed = {
            str(value)
            for value in raw.get("allowed_arguments") or []
            if str(value)
        }
        if not name:
            continue
        by_tool[name] = allowed
        for argument in allowed:
            owners.setdefault(argument, []).append(name)
    return by_tool, {
        argument: sorted(set(tool_names))
        for argument, tool_names in owners.items()
    }


def _loop_guard_identity_index(
    contract: Mapping[str, Any],
) -> dict[str, tuple[str, ...]]:
    index: dict[str, tuple[str, ...]] = {}
    # Generated contracts may add further mutator groups (for example linkers).
    # Any top-level tool entry with identity_args participates in the same guard.
    groups = list(contract.values())
    for group in groups:
        if not isinstance(group, list):
            continue
        for raw in group:
            if not isinstance(raw, Mapping):
                continue
            name = str(raw.get("name") or "")
            args = tuple(
                str(item) for item in (raw.get("identity_args") or []) if str(item)
            )
            if name and args:
                index[name] = args
    return index


def _occurrence_identity(
    call: Mapping[str, Any],
    identity_index: Mapping[str, tuple[str, ...]],
) -> tuple[str, tuple[str, ...]] | None:
    name = str(call.get("name") or "")
    keys = identity_index.get(name)
    if not keys:
        return None
    args = call.get("args") or {}
    values: list[str] = []
    for key in keys:
        value = str((args or {}).get(key) or "").strip()
        if not value:
            return None
        values.append(value)
    return name, tuple(values)


def _fallback_call_identity(
    call: Mapping[str, Any],
) -> tuple[str, tuple[str, ...]] | None:
    name = str(call.get("name") or "").strip()
    args = call.get("args") or {}
    if not name or not isinstance(args, Mapping):
        return None
    return name, ("args_sha256", _canonical_args_sha256(args))


def _call_guard_identity(
    call: Mapping[str, Any],
    identity_index: Mapping[str, tuple[str, ...]],
) -> tuple[str, tuple[str, ...]] | None:
    name = str(call.get("name") or "")
    if name in identity_index:
        return _occurrence_identity(call, identity_index)
    return _fallback_call_identity(call)


def _parsed_tool_receipt(message: ToolMessage) -> dict[str, Any] | None:
    try:
        parsed = json.loads(
            _normalize_ai_message_content(getattr(message, "content", None))
        )
    except Exception:
        return None
    return parsed if isinstance(parsed, dict) else None


def _no_progress_threshold() -> int:
    raw = str(os.environ.get("TWA_REACT_NO_PROGRESS_THRESHOLD") or "3").strip()
    try:
        return max(1, int(raw))
    except ValueError:
        return 3


def _completed_react_turns(
    messages: List[Any],
) -> list[tuple[AIMessage, list[dict[str, Any]]]]:
    identity_index = _loop_guard_identity_index(
        load_occurrence_loop_guard_contract()
    )
    output_by_id = {
        str(getattr(message, "tool_call_id", "") or ""): message
        for message in messages
        if isinstance(message, ToolMessage)
    }
    completed: list[tuple[AIMessage, list[dict[str, Any]]]] = []
    for message in messages:
        if not isinstance(message, AIMessage):
            continue
        calls = list(getattr(message, "tool_calls", []) or [])
        if not calls:
            continue
        receipts: list[dict[str, Any]] = []
        for call in calls:
            output = output_by_id.get(str((call or {}).get("id") or ""))
            if output is None:
                receipts = []
                break
            parsed = _parsed_tool_receipt(output)
            parsed = _normalized_tool_error_payload(
                content=_normalize_ai_message_content(
                    getattr(output, "content", None)
                ),
                status=str(getattr(output, "status", "") or ""),
                call=call or {},
                identity_index=identity_index,
                parsed=parsed,
            )
            if parsed is None:
                receipts = []
                break
            receipts.append(parsed)
        if receipts:
            completed.append((message, receipts))
    return completed


def _explicit_no_progress_turn(
    receipts: list[dict[str, Any]],
) -> bool:
    """Only classify a turn when every receipt exposes authoritative progress."""
    if not receipts:
        return False
    for receipt in receipts:
        if receipt.get("graph_changed") is False:
            continue
        # A stable before/after revision is an equivalent explicit signal.
        before = receipt.get("graph_revision_before")
        after = receipt.get("graph_revision_after")
        if before is not None and after is not None and before == after:
            continue
        return False
    return True


def _forced_extra_argument_repair(
    messages: List[Any],
) -> Dict[str, Any]:
    """Retry one pre-execution call after safely removing only extra kwargs."""
    if not messages or not isinstance(messages[-1], AIMessage):
        return {}
    if list(getattr(messages[-1], "tool_calls", []) or []):
        return {}
    identity_index = _loop_guard_identity_index(
        load_occurrence_loop_guard_contract()
    )
    output_by_id = {
        str(getattr(message, "tool_call_id", "") or ""): message
        for message in messages
        if isinstance(message, ToolMessage)
    }
    all_call_ids: set[str] = set()
    pending: dict[str, tuple[dict[str, Any], dict[str, Any]]] = {}
    for message in messages:
        if not isinstance(message, AIMessage):
            continue
        for raw_call in list(getattr(message, "tool_calls", []) or []):
            call = dict(raw_call or {})
            call_id = str(call.get("id") or "")
            if call_id:
                all_call_ids.add(call_id)
            output = output_by_id.get(call_id)
            if output is None:
                continue
            content = _normalize_ai_message_content(
                getattr(output, "content", None)
            )
            parsed = _parsed_tool_receipt(output)
            payload = _normalized_tool_error_payload(
                content=content,
                status=str(getattr(output, "status", "") or ""),
                call=call,
                identity_index=identity_index,
                parsed=parsed,
            )
            if not isinstance(payload, dict):
                continue
            fingerprint = str(
                payload.get("semantic_fingerprint")
                or _semantic_call_fingerprint(call, identity_index)
                or call_id
            )
            status = str(payload.get("status") or "").casefold()
            if status == "ok":
                pending.pop(fingerprint, None)
            elif (
                payload.get("code") == "TOOL_ARGUMENT_VALIDATION"
                and payload.get("auto_repairable_extra_arguments") is True
                and payload.get("invalid_arguments")
            ):
                pending[fingerprint] = (call, payload)
    if not pending:
        return {}
    call, payload = next(reversed(pending.values()))
    original_id = str(call.get("id") or "")
    if original_id.startswith("schema-repair-"):
        return {}
    repair_id = (
        "schema-repair-"
        + hashlib.sha256(original_id.encode("utf-8")).hexdigest()[:16]
    )
    if repair_id in all_call_ids:
        return {}
    invalid = {
        str(value) for value in payload.get("invalid_arguments") or []
    }
    original_args = dict(call.get("args") or call.get("arguments") or {})
    corrected_args = {
        key: value
        for key, value in original_args.items()
        if str(key) not in invalid
    }
    if not corrected_args or corrected_args == original_args:
        return {}
    repair_notice = {
        "status": "repairing",
        "code": "AUTO_RETRY_WITHOUT_EXTRA_ARGUMENTS",
        "tool_name": str(call.get("name") or ""),
        "removed_arguments": sorted(invalid),
        "argument_owners": payload.get("argument_owners") or {},
        "instruction": (
            "Executing one safe retry of the original occurrence without unsupported "
            "arguments. Removed fields remain visible in history and may be routed to "
            "their owning tool only when independently supported by the ledger."
        ),
    }
    return {
        "messages": [
            AIMessage(
                content=json.dumps(
                    repair_notice,
                    ensure_ascii=False,
                    sort_keys=True,
                ),
                tool_calls=[
                    {
                        "id": repair_id,
                        "name": str(call.get("name") or ""),
                        "args": corrected_args,
                    }
                ],
            )
        ]
    }


def _rewrite_latest_call_through_argument_firewall(
    messages: List[Any],
) -> Dict[str, Any]:
    """Remove only contract-unknown kwargs before tool schema validation."""
    if not messages or not isinstance(messages[-1], AIMessage):
        return {}
    latest = messages[-1]
    calls = list(getattr(latest, "tool_calls", []) or [])
    if not calls:
        return {}
    allowed_by_tool, owners_by_argument = _argument_contract_indexes()
    rewritten_calls: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []
    for raw_call in calls:
        call = dict(raw_call or {})
        name = str(call.get("name") or "").strip()
        args = dict(call.get("args") or call.get("arguments") or {})
        if name not in allowed_by_tool:
            rewritten_calls.append(call)
            continue
        allowed = allowed_by_tool[name]
        invalid = sorted(str(key) for key in args if str(key) not in allowed)
        if not invalid:
            rewritten_calls.append(call)
            continue
        call["args"] = {
            key: value for key, value in args.items() if str(key) in allowed
        }
        call.pop("arguments", None)
        rewritten_calls.append(call)
        warnings.append(
            {
                "call_id": str(call.get("id") or ""),
                "tool_name": name,
                "removed_arguments": invalid,
                "removed_facets": [
                    {
                        "argument": argument,
                        "value": _compact_receipt_value(args.get(argument)),
                        "owner_candidates": [
                            owner
                            for owner in owners_by_argument.get(argument, [])
                            if owner != name
                        ],
                        "disposition": "omitted_from_selected_occurrence",
                        "reason": "argument_not_owned_by_selected_tool",
                    }
                    for argument in invalid
                ],
                "argument_owners": {
                    argument: [
                        owner
                        for owner in owners_by_argument.get(argument, [])
                        if owner != name
                    ]
                    for argument in invalid
                },
                "original_args_sha256": _canonical_args_sha256(args),
                "skip_receipt": {
                    "policy": "preserve_legal_subset_over_rejecting_entity",
                    "evidence": "generated_argument_ownership_contract",
                    "controlled": True,
                },
                "policy": (
                    "The legal subset is executed. Removed arguments are not "
                    "automatically routed to another occurrence."
                ),
            }
        )
    if not warnings:
        return {}
    firewall_payload = {
        "schema_version": "react-argument-firewall.v1",
        "status": "warning",
        "code": "ARGUMENT_FIREWALL_SANITIZED",
        "warnings": warnings,
        "instruction": (
            "The listed unsupported arguments were removed before execution. "
            "Use an owner candidate only if the source ledger independently "
            "supports that separate occurrence; never invent one to preserve a field."
        ),
    }
    additional_kwargs = dict(getattr(latest, "additional_kwargs", {}) or {})
    additional_kwargs.pop("tool_calls", None)
    additional_kwargs["argument_firewall"] = firewall_payload
    original_content = _normalize_ai_message_content(
        getattr(latest, "content", None)
    ).strip()
    notice = json.dumps(firewall_payload, ensure_ascii=False, sort_keys=True)
    content = f"{original_content}\n\n{notice}".strip()
    message_id = getattr(latest, "id", None)
    if not message_id:
        return {}
    replacement = latest.model_copy(
        update={
            "content": content,
            "tool_calls": rewritten_calls,
            "additional_kwargs": additional_kwargs,
            "id": message_id,
        }
    )
    return {"messages": [replacement]}


def _no_progress_stop(
    messages: List[Any],
) -> Dict[str, Any]:
    threshold = _no_progress_threshold()
    completed = _completed_react_turns(messages[:-1])
    consecutive: list[tuple[AIMessage, list[dict[str, Any]]]] = []
    for turn in reversed(completed):
        if not _explicit_no_progress_turn(turn[1]):
            break
        consecutive.append(turn)
    if len(consecutive) < threshold:
        return {}

    receipts = [receipt for _, turn in reversed(consecutive) for receipt in turn]
    fingerprints = sorted(
        {
            str(receipt.get("semantic_fingerprint") or receipt.get("fingerprint"))
            for receipt in receipts
            if receipt.get("semantic_fingerprint") or receipt.get("fingerprint")
        }
    )
    revisions = [
        receipt.get("graph_revision")
        for receipt in receipts
        if receipt.get("graph_revision") is not None
    ]
    payload = {
        "status": "error",
        "code": "react_no_progress",
        "stop_reason": "no_graph_progress",
        "message": (
            f"Stopped after {len(consecutive)} consecutive tool turns with "
            "authoritative graph_changed=false or unchanged graph revision."
        ),
        "threshold": threshold,
        "no_progress_turns": len(consecutive),
        "last_graph_revision": revisions[-1] if revisions else None,
        "semantic_fingerprints": fingerprints,
        "pipeline_action": "finalize_or_repair",
    }
    return {
        "messages": [
            AIMessage(content=json.dumps(payload, ensure_ascii=False, sort_keys=True))
        ]
    }


def _graph_cycle_stop(messages: List[Any]) -> Dict[str, Any]:
    """Stop only cycles backed by both semantic and graph-revision evidence."""
    threshold = _no_progress_threshold()
    completed = _completed_react_turns(messages[:-1])
    markers: list[tuple[tuple[str, ...], tuple[str, ...]]] = []
    for _, receipts in completed:
        fingerprints = [
            str(receipt.get("semantic_fingerprint") or receipt.get("fingerprint") or "")
            for receipt in receipts
        ]
        revisions = [
            receipt.get("graph_revision")
            for receipt in receipts
        ]
        if not all(fingerprints) or any(revision is None for revision in revisions):
            markers.append(((), ()))
            continue
        markers.append(
            (
                tuple(sorted(fingerprints)),
                tuple(str(revision) for revision in revisions),
            )
        )

    detected_period = 0
    for period in range(1, min(3, len(markers) // threshold) + 1):
        window = markers[-period * threshold :]
        if any(not fingerprints for fingerprints, _ in window):
            continue
        if all(window[offset : offset + period] == window[:period]
               for offset in range(period, len(window), period)):
            detected_period = period
            break
    if not detected_period:
        return {}

    cycle = markers[-detected_period:]
    payload = {
        "status": "error",
        "code": "react_graph_cycle",
        "stop_reason": "repeating_graph_cycle",
        "message": (
            f"Stopped a repeated semantic/graph-revision cycle of period "
            f"{detected_period} after {threshold} repetitions."
        ),
        "threshold": threshold,
        "cycle_period": detected_period,
        "cycle": [
            {
                "semantic_fingerprints": list(fingerprints),
                "graph_revisions": list(revisions),
            }
            for fingerprints, revisions in cycle
        ],
        "pipeline_action": "repair",
    }
    return {
        "messages": [
            AIMessage(content=json.dumps(payload, ensure_ascii=False, sort_keys=True))
        ]
    }


def stop_repeated_committed_output_calls(
    state: Dict[str, Any],
    contract: Mapping[str, Any] | None = None,
    *,
    argument_firewall: bool = False,
) -> Dict[str, Any]:
    """Bound replay loops without prematurely ending a generated occurrence plan."""
    spec = contract if contract is not None else load_occurrence_loop_guard_contract()
    identity_index = _loop_guard_identity_index(spec)
    messages = list(state.get("messages") or [])
    if not messages or not isinstance(messages[-1], AIMessage):
        return {}
    if argument_firewall:
        firewall_rewrite = _rewrite_latest_call_through_argument_firewall(messages)
        if firewall_rewrite:
            return firewall_rewrite
    else:
        forced_repair = _forced_extra_argument_repair(messages)
        if forced_repair:
            return forced_repair
    progress_stop = _no_progress_stop(messages)
    if progress_stop:
        return progress_stop
    cycle_stop = _graph_cycle_stop(messages)
    if cycle_stop:
        return cycle_stop
    latest_calls = list(getattr(messages[-1], "tool_calls", []) or [])
    latest_identities = [
        _call_guard_identity(call or {}, identity_index) for call in latest_calls
    ]
    if not latest_calls or any(item is None for item in latest_identities):
        return {}

    committed: set[tuple[str, tuple[str, ...]]] = set()
    output_by_id = {
        str(getattr(message, "tool_call_id", "") or ""): message
        for message in messages[:-1]
        if isinstance(message, ToolMessage)
    }
    for message in messages[:-1]:
        if not isinstance(message, AIMessage):
            continue
        for call in list(getattr(message, "tool_calls", []) or []):
            identity = _call_guard_identity(call or {}, identity_index)
            if identity is None:
                continue
            call_id = str((call or {}).get("id") or "")
            output = output_by_id.get(call_id)
            if output is None:
                continue
            parsed = _parsed_tool_receipt(output)
            if parsed is None:
                continue
            if str((parsed or {}).get("status") or "").lower() == "ok":
                committed.add(identity)

    if not committed or not set(latest_identities).issubset(committed):
        return {}
    # Generated contracts cover the complete mutation surface and return
    # authoritative graph progress receipts. Let the replay execute so the
    # model can observe ``already_committed`` and continue remaining ledger
    # obligations; the bounded no-progress/cycle checks above stop persistent
    # replay. Keep the legacy immediate stop only for the narrow v4 fallback.
    if spec.get("mutation_tools"):
        return {}
    return {
        "messages": [
            AIMessage(
                content=json.dumps(
                    {
                        "status": "stopped",
                        "code": "react_duplicate_committed_calls",
                        "stop_reason": "already_committed",
                        "message": (
                            "Stopped duplicate committed occurrence call: the "
                            "occurrence is already committed. Finalize the current graph."
                        ),
                        "operations": sorted(
                            {
                                str((call or {}).get("name") or "")
                                for call in latest_calls
                            }
                        ),
                        "pipeline_action": "finalize",
                    },
                    ensure_ascii=False,
                    sort_keys=True,
                )
            )
        ]
    }


def _tool_error_text(
    exc: BaseException,
    *,
    tool_name: str = "",
    allowed_arguments: list[str] | None = None,
) -> str:
    """Convert a tool exception into a recoverable observation for ReAct."""
    details = exception_details(exc)
    validation = _looks_like_argument_validation_error(
        str(exc),
        {"error_type": type(exc).__name__, "errors": details},
    )
    payload: dict[str, Any] = {
        "status": "error",
        "code": (
            "TOOL_ARGUMENT_VALIDATION" if validation else "TOOL_EXECUTION_ERROR"
        ),
        "ok": False,
        "error_type": type(exc).__name__,
        "errors": details,
        "instruction": (
            "Correct the tool arguments and retry. Do not treat this tool failure "
            "as successful completion."
        ),
    }
    if tool_name:
        payload["tool_name"] = tool_name
    if allowed_arguments:
        payload["allowed_arguments"] = allowed_arguments
    if validation:
        payload.update(
            {
                "graph_changed": False,
                "pre_execution_error": True,
                "retryable": True,
            }
        )
    return json.dumps(
        payload,
        ensure_ascii=False,
    )


def _tool_error_handler(tool: Any):
    name = str(getattr(tool, "name", "") or "")
    allowed: list[str] = []
    schema = getattr(tool, "args_schema", None)
    try:
        if schema is not None:
            properties = schema.model_json_schema().get("properties") or {}
            allowed = sorted(str(key) for key in properties)
    except Exception:
        allowed = []

    def handle(exc: BaseException) -> str:
        return _tool_error_text(
            exc,
            tool_name=name,
            allowed_arguments=allowed,
        )

    return handle


def _normalize_ai_message_content(content: Any) -> str:
    """
    Turn LangChain AIMessage.content into a plain string.

    ReAct runs may end with ``content=[]`` (tool-only / multimodal blocks with no text).
    Calling ``str([])`` would yield ``\"[]\"`` (2 chars) and break downstream checks — avoid that.
    """
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    if isinstance(content, dict):
        if content.get("type") == "text" and "text" in content:
            return str(content["text"])
        if "text" in content:
            return str(content["text"])
        return ""
    if isinstance(content, list):
        parts: List[str] = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict):
                if block.get("type") == "text" and "text" in block:
                    parts.append(str(block["text"]))
                elif "text" in block:
                    parts.append(str(block["text"]))
            else:
                parts.append(str(block))
        return "".join(parts)
    return str(content)


def _is_trivial_agent_reply(text: str) -> bool:
    """
    True if the model reply is an empty / placeholder token we should not treat as final output.

    ReAct often ends with ``{}`` / ``[]`` or ``str([])``-style noise; the real JSON may appear
    on an earlier AIMessage turn.
    """
    t = (text or "").strip()
    if not t:
        return True
    if t in ("{}", "[]"):
        return True
    if len(t) <= 3 and t.lower().rstrip(".") in ("ok", "yes", "no"):
        return True
    return False


def _best_text_and_meta_from_react_messages(messages: List[Any]) -> Tuple[str, Dict[str, Any]]:
    """
    Prefer the **last** AIMessage whose normalized text is substantive (non-trivial).

    If the graph ends with an empty AIMessage (``content=[]``) or a placeholder ``{}``/``[]``,
    walk backwards so we still return the model's last useful reply.
    """
    if not messages:
        return "", {}

    ai_messages: List[AIMessage] = [m for m in messages if isinstance(m, AIMessage)]
    if not ai_messages:
        last = messages[-1]
        meta = getattr(last, "response_metadata", {}) or {}
        return _normalize_ai_message_content(getattr(last, "content", None)), meta

    for msg in reversed(ai_messages):
        text = _normalize_ai_message_content(msg.content)
        if text.strip() and not _is_trivial_agent_reply(text):
            meta = getattr(msg, "response_metadata", {}) or {}
            return text, meta

    last_ai = ai_messages[-1]
    meta = getattr(last_ai, "response_metadata", {}) or {}
    return _normalize_ai_message_content(last_ai.content), meta


def _summarize_react_tool_activity(
    messages: List[Any],
    *,
    classify_argument_owner_mismatch: bool = False,
) -> Dict[str, Any]:
    """
    Summarize actual tool activity observed in a ReAct run.

    This inspects both:
    - `AIMessage.tool_calls` planned by the model
    - `ToolMessage` objects emitted after tool execution
    """
    ai_messages: List[AIMessage] = [m for m in messages if isinstance(m, AIMessage)]
    tool_messages: List[ToolMessage] = [m for m in messages if isinstance(m, ToolMessage)]
    identity_index = _loop_guard_identity_index(
        load_occurrence_loop_guard_contract()
    )

    tool_call_names: List[str] = []
    planned_tool_calls: List[Dict[str, Any]] = []
    planned_by_id: Dict[str, Dict[str, Any]] = {}
    for msg in ai_messages:
        firewall_payload = (
            getattr(msg, "additional_kwargs", {}) or {}
        ).get("argument_firewall")
        firewall_by_call = {
            str(item.get("call_id") or ""): dict(item)
            for item in (
                firewall_payload.get("warnings") or []
                if isinstance(firewall_payload, Mapping)
                else []
            )
            if isinstance(item, Mapping)
        }
        for call in getattr(msg, "tool_calls", []) or []:
            name = str((call or {}).get("name") or "").strip()
            if name:
                tool_call_names.append(name)
            planned = {
                "id": str((call or {}).get("id") or ""),
                "name": name,
                "args": (call or {}).get("args"),
            }
            semantic_fingerprint = _semantic_call_fingerprint(
                call or {},
                identity_index,
            )
            if semantic_fingerprint:
                planned["semantic_fingerprint"] = semantic_fingerprint
            call_id = str(planned["id"])
            if call_id in firewall_by_call:
                planned["argument_firewall_warning"] = firewall_by_call[call_id]
            planned_tool_calls.append(planned)
            if planned["id"]:
                planned_by_id[planned["id"]] = planned

    executed_tool_names: List[str] = []
    tool_outputs: List[Dict[str, Any]] = []
    for msg in tool_messages:
        name = str(getattr(msg, "name", "") or "").strip()
        if name:
            executed_tool_names.append(name)
        content = _normalize_ai_message_content(getattr(msg, "content", None))
        parsed_content: Any = None
        if content:
            try:
                parsed_content = json.loads(content)
            except (TypeError, ValueError):
                parsed_content = None
        call_id = str(getattr(msg, "tool_call_id", "") or "")
        planned = planned_by_id.get(call_id) or {}
        parsed_content = _normalized_tool_error_payload(
            content=content,
            status=str(getattr(msg, "status", "") or ""),
            call=planned,
            identity_index=identity_index,
            parsed=parsed_content,
            classify_argument_owner_mismatch=classify_argument_owner_mismatch,
        )
        output = {
            "tool_call_id": call_id,
            "name": name or str(planned.get("name") or ""),
            "status": str(getattr(msg, "status", "") or ""),
            "content": content,
            "structured_content": parsed_content,
        }
        semantic_fingerprint = str(
            (parsed_content or {}).get("semantic_fingerprint")
            or planned.get("semantic_fingerprint")
            or ""
        )
        if semantic_fingerprint:
            output["semantic_fingerprint"] = semantic_fingerprint
        tool_outputs.append(output)

    return {
        "ai_message_count": len(ai_messages),
        "tool_message_count": len(tool_messages),
        "planned_tool_call_count": len(tool_call_names),
        "planned_tool_names": tool_call_names,
        "planned_tool_calls": planned_tool_calls,
        "executed_tool_names": executed_tool_names,
        "executed_tool_name_set": sorted(set(executed_tool_names)),
        "tool_outputs": tool_outputs,
    }


def _required_final_call_satisfied(
    tool_activity: Dict[str, Any],
    *,
    tool_name: str,
    required_arguments: Dict[str, Any] | None,
) -> bool:
    """Return whether the final executed tool has the exact required call contract."""
    outputs = list(tool_activity.get("tool_outputs") or [])
    if not outputs:
        return False

    final_output = outputs[-1] or {}
    if str(final_output.get("name") or "").strip() != tool_name:
        return False

    # Preserve the historical name-only contract when no canonical arguments
    # were supplied by the caller.
    if required_arguments is None:
        return True

    final_call_id = str(final_output.get("tool_call_id") or "")
    if not final_call_id:
        return False

    for planned_call in reversed(tool_activity.get("planned_tool_calls") or []):
        if str((planned_call or {}).get("id") or "") != final_call_id:
            continue
        return (planned_call or {}).get("args") == required_arguments
    return False


def _mcp_result_content(result: Any) -> tuple[str, Any]:
    """Normalize a direct MCP fallback result for downstream trace handling."""
    structured = getattr(result, "structuredContent", None)
    if isinstance(structured, dict):
        payload = structured.get("result", structured)
        if isinstance(payload, str):
            try:
                return payload, json.loads(payload)
            except (TypeError, ValueError):
                return payload, None
        return json.dumps(payload, ensure_ascii=False, default=str), payload
    parts = getattr(result, "content", None) or []
    text = "".join(
        str(getattr(part, "text", "") or "")
        for part in parts
    ).strip()
    try:
        parsed = json.loads(text) if text else None
    except (TypeError, ValueError):
        parsed = None
    return text, parsed


def _is_structured_tool_rejection(result: Any, structured: Any) -> bool:
    """Detect transport errors and standard structured rejection envelopes."""
    if bool(getattr(result, "isError", False)):
        return True
    if not isinstance(structured, dict):
        return False
    return structured.get("ok") is False or str(
        structured.get("status") or ""
    ).casefold() in {"rejected", "error", "failed"}


async def _call_required_mcp_tool(
    session: Any,
    *,
    tool_name: str,
    arguments: Dict[str, Any] | None = None,
    phase: str,
) -> Dict[str, Any]:
    """Call a pipeline-required MCP tool and reject structured failures."""
    try:
        result = await session.call_tool(tool_name, dict(arguments or {}))
    except BaseException as exc:
        if isinstance(exc, (KeyboardInterrupt, SystemExit)):
            raise
        leaves = exception_details(exc)
        detail = "; ".join(
            f"{item['type']}: {item['message']}" for item in leaves
        ) or str(exc)
        raise RuntimeError(
            f"Required {phase} MCP tool `{tool_name}` failed: {detail}"
        ) from exc
    content, structured = _mcp_result_content(result)
    rejected = _is_structured_tool_rejection(result, structured)
    output = {
        "tool_call_id": f"pipeline-required-{phase}-tool",
        "name": tool_name,
        "status": "error" if rejected else "success",
        "content": content,
        "structured_content": structured,
        "script_fallback": phase == "final",
        "pipeline_required": True,
        "phase": phase,
    }
    if rejected:
        raise RuntimeError(
            f"Required {phase} MCP tool `{tool_name}` was rejected: {content}"
        )
    return output


class BaseAgent:
    # ──────────────────────────── init ────────────────────────────
    def __init__(
        self,
        model_name: str = "gpt-4o-mini",
        remote_model: bool = True,
        model_config: ModelConfig | None = None,
        mcp_set_name: str | None = "mcp_configs.json",
        mcp_tools: List[str] | None = None,
        excluded_tool_names: List[str] | None = None,
        structured_output: bool = False,
        structured_output_schema: Any = None,
    ):
        self.model_name = model_name
        self.remote_model = remote_model
        self.model_config = model_config or ModelConfig()
        self.mcp_config = MCPConfig(config_name=mcp_set_name)
        self.mcp_tools = mcp_tools or ["github", "filesystem"]
        self.excluded_tool_names = {
            str(value).strip()
            for value in (excluded_tool_names or [])
            if str(value).strip()
        }
        self.logger = get_logger("agent", "BaseAgent")

        self.llm = LLMCreator(
            model=self.model_name,
            remote_model=self.remote_model,
            model_config=self.model_config,
            structured_output=structured_output,
            structured_output_schema=structured_output_schema,
        ).setup_llm()

    # ──────────────────────────── run ────────────────────────────
    async def run(
        self,
        task_instruction: str,
        recursion_limit: int | None = None,
        required_initial_tool: str | None = None,
        required_initial_tool_args: Dict[str, Any] | None = None,
        required_final_tool: str | None = None,
        required_final_tool_args: Dict[str, Any] | None = None,
        mcp_instruction_in_user: bool = False,
        task_continuation: str | None = None,
        react_history_projection: bool = False,
        react_argument_firewall: bool = False,
    ) -> Tuple[str, Dict[str, Any]]:
        """
        Execute *task_instruction* through a ReAct agent wired to MCP tools.

        A required initial tool runs after its MCP session opens and before the
        agent starts. A missing final tool is called as a fallback on that same
        tool-bound session before the session is closed.

        When *mcp_instruction_in_user* is true, the MCP ``instruction`` prompt
        is inserted between *task_instruction* (case bindings) and
        *task_continuation* (lifecycle / manifests / recovery). It is not
        wrapped as a system message.
        """
        # Truncate task instruction for logging to avoid console spam
        task_preview = task_instruction[:200] + "..." if len(task_instruction) > 200 else task_instruction
        self.logger.info(f"Starting BaseAgent run with task: {task_preview}")
        parent_call_id = uuid4().hex
        
        # 1️⃣ MCP configs
        server_cfg = self.mcp_config.get_config(self.mcp_tools)
        self.logger.info(f"Loaded MCP tools: {self.mcp_tools}")
        
        # Compatibility: some MCP client stacks (depending on installed `mcp` version) do not accept a
        # `description` kwarg when creating stdio sessions. Our config files sometimes include it
        # (e.g., `configs/mops_mcp.json` for the `document` server). Strip it to avoid runtime errors.
        #
        # Also merge the parent process environment into each server's env. Config JSON `env`
        # blocks otherwise *replace* the process environment and drop critical keys such as
        # TWA_AGENTIC_DATA_DIR (pipeline seeds runtime/<hash>/memory, but MCP would open data/).
        try:
            merged_cfg: Dict[str, Any] = {}
            for name, cfg in (server_cfg or {}).items():
                clean = {
                    k: v for k, v in (cfg or {}).items() if k != "description"
                }
                clean["env"] = _merge_mcp_server_environment(
                    dict(clean.get("env") or {}),
                    dict(os.environ),
                )
                merged_cfg[name] = clean
            server_cfg = merged_cfg
        except Exception:
            # If sanitization fails for any reason, fall back to the raw config.
            pass

        # 2️⃣ Docker check (non-fatal)
        #
        # Many MCP servers in this repo are pure local stdio Python servers and do NOT require Docker.
        # Some optional external MCP servers do. Keep this as a warning to avoid confusion/noise.
        try:
            docker_running = await self.mcp_config.is_docker_running()
        except Exception:
            docker_running = False
        if not docker_running:
            self.logger.warning(
                "Docker is not running (this is OK for local stdio MCP servers; "
                "only Docker-based MCP servers require it)."
            )

        # 3️⃣ Multi-server MCP client
        #
        # IMPORTANT: langchain-mcp-adapters 0.1.0 does NOT allow `async with MultiServerMCPClient(...)`.
        # To ensure deterministic cleanup and avoid spawning a new stdio server process on every tool call,
        # we open one session per configured MCP server for the duration of this run.
        mcp_client = MultiServerMCPClient(server_cfg)

        reply_text = ""
        meta: Dict[str, Any] = {}
        final_call_token_usage: Dict[str, Any] = {}
        required_initial_tool_call: Dict[str, Any] | None = None

        async with AsyncExitStack() as stack:
            sessions: Dict[str, Any] = {}
            for server_name in self.mcp_tools:
                try:
                    session = await stack.enter_async_context(mcp_client.session(server_name))
                    sessions[server_name] = session
                except Exception as exc:
                    self.logger.error(f"Could not open MCP session for '{server_name}': {exc}")
                    raise RuntimeError(f"Could not open MCP session for '{server_name}': {exc}") from exc

            # Load tools bound to the open sessions (so tool calls reuse the session)
            tools = []
            tool_sessions: Dict[str, Any] = {}
            for server_name, session in sessions.items():
                try:
                    server_tools = await load_mcp_tools(session)
                    excluded = [
                        tool
                        for tool in server_tools
                        if str(getattr(tool, "name", "") or "").strip()
                        in self.excluded_tool_names
                    ]
                    server_tools = [
                        tool
                        for tool in server_tools
                        if str(getattr(tool, "name", "") or "").strip()
                        not in self.excluded_tool_names
                    ]
                    if excluded:
                        self.logger.info(
                            "Excluded MCP tools from %s: %s",
                            server_name,
                            sorted(
                                str(getattr(tool, "name", "") or "")
                                for tool in excluded
                            ),
                        )
                    for tool in server_tools:
                        if hasattr(tool, "handle_tool_error"):
                            tool.handle_tool_error = _tool_error_handler(tool)
                        tool_name = str(getattr(tool, "name", "") or "").strip()
                        if tool_name:
                            tool_sessions[tool_name] = session
                    tools.extend(server_tools)
                    self.logger.info(f"Loaded {len(server_tools)} MCP tools from {server_name}")
                except Exception as exc:
                    self.logger.error(f"Could not load MCP tools from '{server_name}': {exc}")
                    raise RuntimeError(f"Could not load MCP tools from '{server_name}': {exc}") from exc

            if not tools:
                self.logger.error("No MCP tools were successfully loaded.")
                raise RuntimeError("No MCP tools were successfully loaded.")
            required_initial_name = str(required_initial_tool or "").strip()
            if required_initial_name:
                initial_session = tool_sessions.get(required_initial_name)
                if initial_session is None:
                    raise RuntimeError(
                        f"Required initial MCP tool `{required_initial_name}` "
                        "is not exposed by the open sessions"
                    )
                required_initial_tool_call = await _call_required_mcp_tool(
                    initial_session,
                    tool_name=required_initial_name,
                    arguments=required_initial_tool_args,
                    phase="initial",
                )
                self.logger.info(
                    "Required initial MCP tool `%s` completed before agent execution",
                    required_initial_name,
                )

            # optional instruction prompts (fetch every time as they may change)
            instruction_msgs = []
            for server_name, session in sessions.items():
                try:
                    msgs = await load_mcp_prompt(session, "instruction")
                    instruction_msgs.extend(msgs)
                    self.logger.info(f"Loaded instruction prompt from {server_name}")
                except Exception as e:
                    self.logger.warning(f"'{server_name}' lacks an 'instruction' prompt ({e})")

            if mcp_instruction_in_user:
                if not instruction_msgs:
                    raise RuntimeError(
                        "MCP user-message instruction delivery requested, but no "
                        "'instruction' prompt was exposed"
                    )
                task_instruction = compose_user_message_with_mcp_instruction(
                    task_instruction=task_instruction,
                    mcp_instruction="\n\n".join(
                        str(message.content) for message in instruction_msgs
                    ),
                    task_continuation=task_continuation or "",
                )
                instruction_msgs = []
                self.logger.info(
                    "Inserted MCP instruction between the case bindings and runtime continuation"
                )

            # 4️⃣ ReAct agent
            def occurrence_pre_model_hook(state: Dict[str, Any]) -> Dict[str, Any]:
                return project_react_history_to_receipts(
                    state,
                    classify_argument_owner_mismatch=react_argument_firewall,
                )

            def occurrence_post_model_hook(state: Dict[str, Any]) -> Dict[str, Any]:
                return stop_repeated_committed_output_calls(
                    state,
                    argument_firewall=react_argument_firewall,
                )

            if instruction_msgs:
                system_text = "\n\n".join(m.content for m in instruction_msgs)
                prompt = ChatPromptTemplate.from_messages(
                    [
                        ("system", system_text),
                        MessagesPlaceholder("messages"),
                    ]
                )
                agent = create_react_agent(
                    self.llm,
                    tools,
                    prompt=prompt,
                    pre_model_hook=(
                        occurrence_pre_model_hook
                        if react_history_projection
                        else None
                    ),
                    post_model_hook=(
                        occurrence_post_model_hook
                        if react_history_projection or react_argument_firewall
                        else None
                    ),
                )
                self.logger.info("Created ReAct agent with custom prompt")
            else:
                agent = create_react_agent(
                    self.llm,
                    tools,
                    pre_model_hook=(
                        occurrence_pre_model_hook
                        if react_history_projection
                        else None
                    ),
                    post_model_hook=(
                        occurrence_post_model_hook
                        if react_history_projection or react_argument_firewall
                        else None
                    ),
                )
                self.logger.info("Created ReAct agent with default prompt")

            # 5️⃣ Run with per-call + aggregated accounting
            invoke_kwargs: Dict[str, Any] = {
                "messages": [HumanMessage(content=task_instruction)]
            }
            self.logger.info("Starting agent execution")

            counter = TokenCounter(log_fn=self.logger.info)
            config: Dict[str, Any] = {"callbacks": [counter]}
            if recursion_limit is not None:
                config["recursion_limit"] = recursion_limit

            try:
                with telemetry_context(
                    parent_call_id,
                    {
                        "component": "BaseAgent",
                        "agent_model": self.model_name,
                    },
                ):
                    result = await agent.ainvoke(invoke_kwargs, config)
            except BaseException as e:
                # Python 3.11+: langgraph can raise ExceptionGroup/TaskGroup errors.
                # Surface the nested exceptions so pipeline logs are actionable.
                leaves = exception_details(e)
                if leaves:
                    self.logger.error(
                        "Agent failure leaf cause(s): %s",
                        json.dumps(leaves, ensure_ascii=False),
                    )
                raise
            self.logger.info("Agent execution completed")

            tool_activity = _summarize_react_tool_activity(
                result["messages"],
                classify_argument_owner_mismatch=react_argument_firewall,
            )
            if required_initial_tool_call is not None:
                tool_activity["tool_outputs"].insert(0, required_initial_tool_call)
                tool_activity["executed_tool_names"].insert(
                    0, required_initial_tool_call["name"]
                )
                tool_activity["executed_tool_name_set"] = sorted(
                    set(tool_activity["executed_tool_names"])
                )
                tool_activity["tool_message_count"] += 1
            required_tool_fallback: Dict[str, Any] | None = None
            required_name = str(required_final_tool or "").strip()
            if (
                required_name
                and not _required_final_call_satisfied(
                    tool_activity,
                    tool_name=required_name,
                    required_arguments=required_final_tool_args,
                )
            ):
                session = tool_sessions.get(required_name)
                if session is None:
                    raise RuntimeError(
                        f"Required final MCP tool `{required_name}` "
                        "is not exposed by the open sessions"
                    )
                required_tool_fallback = await _call_required_mcp_tool(
                    session,
                    tool_name=required_name,
                    arguments=required_final_tool_args,
                    phase="final",
                )
                tool_activity["tool_outputs"].append(required_tool_fallback)
                tool_activity["executed_tool_names"].append(required_name)
                tool_activity["executed_tool_name_set"] = sorted(
                    set(tool_activity["executed_tool_names"])
                )
                tool_activity["tool_message_count"] += 1
            self.logger.info(
                "ReAct tool activity: planned_tool_calls=%s, tool_messages=%s, executed_tools=%s",
                tool_activity["planned_tool_call_count"],
                tool_activity["tool_message_count"],
                tool_activity["executed_tool_name_set"],
            )

            # 6️⃣ Final substantive AI reply + meta (last AIMessage may be empty: content=[])
            reply_text, meta = _best_text_and_meta_from_react_messages(result["messages"])
            if not reply_text.strip():
                _aim = [m for m in result["messages"] if isinstance(m, AIMessage)]
                _last_len = (
                    len(_normalize_ai_message_content(_aim[-1].content)) if _aim else 0
                )
                self.logger.warning(
                    "ReAct run ended with no non-empty AIMessage text; last normalized AIMessage length=%s.",
                    _last_len,
                )
            final_call_token_usage = meta.get("token_usage", {})  # may be empty depending on provider

        # Aggregated totals
        aggregated = {
            "prompt_tokens": counter.prompt_tokens,
            "completion_tokens": counter.completion_tokens,
            "total_tokens": counter.total_tokens,
            "calls": counter.calls,
            "estimated_cost_usd": round(
                counter.input_cost_usd + counter.output_cost_usd, 6
            ),
        }
        actual_costs = summarize_costs(journal_path(), parent_call_id)

        # Full metadata payload with both views
        metadata = {
            "model_name": meta.get("model_name", ""),
            "final_call_token_usage": final_call_token_usage,  # last LLM call only
            "aggregated_usage": aggregated,                    # run-level totals
            "per_call_usage": counter.calls_detail,            # list of per-call dicts
            "tool_activity": tool_activity,
            "required_initial_tool_call": required_initial_tool_call,
            "required_final_tool_fallback": required_tool_fallback,
            "parent_call_id": parent_call_id,
            "actual_cost_usd": actual_costs["actual_cost_usd"],
            "pending_cost_count": actual_costs["pending_calls"],
            "resolved_cost_count": actual_costs["resolved_calls"],
            "billable_llm_calls": actual_costs["billable_calls"],
            "generation_ids": actual_costs["generation_ids"],
            "cost_journal": str(journal_path()),
        }

        self.logger.info(
            f"Agent tokens (run-level): {aggregated['total_tokens']} "
            f"over {aggregated['calls']} calls; actual OpenRouter cost "
            f"${actual_costs['actual_cost_usd']:.6f} "
            f"({actual_costs['resolved_calls']} resolved, "
            f"{actual_costs['pending_calls']} pending)"
        )
        return reply_text, metadata


# ─────────────────────────── demo ───────────────────────────
if __name__ == "__main__":

    def _self_test_best_text() -> None:
        """Reproduce str([])->\"[]\" failure: last AIMessage empty, earlier has body."""
        from langchain_core.messages import ToolMessage

        long_body = "x" * 80
        msgs = [
            HumanMessage(content="task"),
            AIMessage(content=long_body),
            ToolMessage(content="{}", tool_call_id="a"),
            AIMessage(content=[]),
        ]
        text, _meta = _best_text_and_meta_from_react_messages(msgs)
        assert text == long_body, (text, len(text))
        assert str([]) == "[]" and len("[]") == 2  # document the old pitfall

        json_prev = '{"entities": [' + '"x",' * 40 + '"z"]}'
        msgs2 = [
            HumanMessage(content="task"),
            AIMessage(content=json_prev),
            AIMessage(content="{}"),
        ]
        text2, _ = _best_text_and_meta_from_react_messages(msgs2)
        assert text2 == json_prev, text2

    _self_test_best_text()
    print("BaseAgent: _best_text self-test OK")

    async def _demo() -> None:
        agent = BaseAgent(mcp_tools=["pubchem", "enhanced_websearch"], mcp_set_name="chemistry.json")
        reply, meta = await agent.run(
            """
            Try to find all representations of the chemical species name: H2edb
            """
        )

        print(reply)
        print(meta["aggregated_usage"])

    # Full MCP demo is opt-in (needs servers / keys).
    import os

    if os.environ.get("BASE_AGENT_RUN_MCP_DEMO") == "1":
        asyncio.run(_demo())
